<?php
namespace App\Console\Commands;
use App\Services\NotificationService;
use App\Services\TemplateEngineService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
final class FinalizeExpiredContracts extends Command
{
    protected $signature='zdraft:finalize-expired-contracts {--limit=50}';protected $description='Lock and issue expired self-service contracts automatically';
    public function __construct(private TemplateEngineService $engine,private NotificationService $notifications){parent::__construct();}
    public function handle():int{$limit=max(1,min(500,(int)$this->option('limit')));$rows=DB::select("SELECT c.id,c.current_version_id,c.template_version_id,c.variant_key,c.selected_optional_clause_keys,c.field_values_json,c.attachment_refs_json,c.serial_number,c.user_id,c.client_user_id,tv.definition_json FROM contracts c JOIN template_versions tv ON tv.id=c.template_version_id WHERE c.creation_mode='self_service' AND c.status='client_review' AND c.edit_expires_at IS NOT NULL AND c.edit_expires_at<=CURRENT_TIMESTAMP AND c.deleted_at IS NULL ORDER BY c.edit_expires_at LIMIT ?",[$limit]);$done=0;foreach($rows as$c){try{$def=$this->json($c->definition_json);$fields=$this->json($c->field_values_json);$optional=$this->list($c->selected_optional_clause_keys);$validation=$this->engine->validateDraft($def,$c->variant_key,$optional,$fields,$this->json($c->attachment_refs_json));if($validation['issues'])throw new \RuntimeException('Incomplete contract: '.implode(', ',$validation['issues']));$rendered=$this->engine->renderLegalClauses($def,$c->variant_key,$optional,$fields);if($rendered['missingClauseKeys']||$rendered['missingVariables'])throw new \RuntimeException('Legal clause snapshot is incomplete');$snapshot=['templateVersionId'=>$c->template_version_id,'variantKey'=>$c->variant_key,'optionalKeys'=>$optional,'fieldValues'=>$fields,'clauses'=>$rendered['clauses']];$hash=hash('sha256',$this->stable($snapshot));DB::transaction(function()use($c,$rendered,$hash){$locked=DB::selectOne("SELECT status FROM contracts WHERE id=? FOR UPDATE",[$c->id]);if(!$locked||$locked->status!=='client_review')return;DB::statement("UPDATE contract_versions SET legal_clause_snapshot_json=?::jsonb,status='issued',document_hash=?,locked_at=CURRENT_TIMESTAMP WHERE id=?",[json_encode($rendered['clauses'],JSON_UNESCAPED_UNICODE),$hash,$c->current_version_id]);DB::statement("UPDATE contracts SET status='issued',core_identity_locked=TRUE,locked_at=CURRENT_TIMESTAMP,issued_at=CURRENT_TIMESTAMP,pdf_status='queued',updated_at=CURRENT_TIMESTAMP WHERE id=?",[$c->id]);DB::insert("INSERT INTO document_jobs(contract_id,contract_version_id,job_type,status,payload_json) VALUES (?,?,'generate_pdf','pending',?::jsonb)",[$c->id,$c->current_version_id,json_encode(['requestedBy'=>'automatic_edit_window_expiry'])]);$this->notifications->notify((int)($c->client_user_id??$c->user_id),'contract_issued','تم إصدار النسخة النهائية',"{$c->serial_number}: انتهت مهلة التعديل ويجري تجهيز ملف PDF","/contract/{$c->id}");});$done++;}catch(\Throwable$e){$this->error("Contract {$c->id}: {$e->getMessage()}");}}$this->info("Finalized {$done} contract(s).");return self::SUCCESS;}
    private function json(mixed$v):array{if(is_array($v))return$v;if(is_object($v))return(array)$v;if(is_string($v))return json_decode($v,true)?:[];return[];}private function list(mixed$v):array{return array_values($this->json($v));}private function stable(mixed$v):string{return json_encode($this->canonical($v),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION);}private function canonical(mixed$v):mixed{if(!is_array($v))return$v;if(array_is_list($v))return array_map(fn($x)=>$this->canonical($x),$v);ksort($v);foreach($v as$k=>$x)$v[$k]=$this->canonical($x);return$v;}
}
