<?php
namespace App\Console\Commands;
use Illuminate\Console\Command;
use Symfony\Component\Process\Process;
final class BackupZDraft extends Command
{
    protected $signature='zdraft:backup {--output=}';protected $description='Create encrypted-ready database and private-files backup archive';
    public function handle():int{$base=$this->option('output')?:storage_path('backups');if(!is_dir($base)&&!mkdir($base,0770,true)&&!is_dir($base)){$this->error('Cannot create backup directory');return self::FAILURE;}$stamp=gmdate('Ymd-His');$work=$base.'/zdraft-'.$stamp;if(!mkdir($work,0770,true)&&!is_dir($work))return self::FAILURE;try{$dump=$work.'/database.dump';$env=array_merge($_ENV,['PGPASSWORD'=>(string)env('DB_PASSWORD')]);$pg=new Process(['pg_dump','--format=custom','--no-owner','--no-acl','--host='.(string)env('DB_HOST','127.0.0.1'),'--port='.(string)env('DB_PORT','5432'),'--username='.(string)env('DB_USERNAME'),'--file='.$dump,(string)env('DB_DATABASE')],null,$env);$pg->setTimeout(600);$pg->mustRun();$manifest=['createdAt'=>now()->toIso8601String(),'database'=>(string)env('DB_DATABASE'),'appVersion'=>'20.0.0','privateStorage'=>config('filesystems.disks.private.root'),'contractsStorage'=>config('filesystems.disks.contracts.root')];file_put_contents($work.'/manifest.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));$archive=$base.'/zdraft-'.$stamp.'.tar.gz';$paths=[$work];foreach([config('filesystems.disks.private.root'),config('filesystems.disks.contracts.root')]as$root)if($root&&is_dir($root))$paths[]=$root;$args=['tar','-czf',$archive];foreach($paths as$p){$args[]='-C';$args[]=dirname($p);$args[]=basename($p);} $tar=new Process($args);$tar->setTimeout(1800);$tar->mustRun();file_put_contents($archive.'.sha256',hash_file('sha256',$archive).'  '.basename($archive).PHP_EOL);$this->info("Backup created: {$archive}");return self::SUCCESS;}catch(\Throwable$e){$this->error($e->getMessage());return self::FAILURE;}finally{$this->remove($work);}}
    private function remove(string$path):void{if(!is_dir($path))return;$it=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::CHILD_FIRST);foreach($it as$f){$f->isDir()?@rmdir($f->getPathname()):@unlink($f->getPathname());}@rmdir($path);}
}
