<?php
namespace App\Console\Commands;

use App\Services\NotificationService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Process\Process;

final class ProcessDocumentJobs extends Command
{
    protected $signature='zdraft:process-documents {--limit=3}';
    protected $description='Generate final contract and annex PDF files using WeasyPrint';
    public function __construct(private NotificationService $notifications){parent::__construct();}

    public function handle():int
    {
        $limit=max(1,min(50,(int)$this->option('limit')));$count=0;
        while($count<$limit){$job=$this->claim();if(!$job)break;try{$this->process($job);$this->info("Completed document job {$job->id}");}catch(\Throwable $e){$this->markFailed($job,$e);$this->error("Document job {$job->id}: {$e->getMessage()}");}$count++;}
        $this->info("Processed {$count} document job(s).");return self::SUCCESS;
    }
    private function claim():?object{return DB::transaction(function(){$row=DB::selectOne("SELECT id,contract_id,contract_version_id,attempts FROM document_jobs WHERE job_type='generate_pdf' AND status IN ('pending','retry') AND available_at<=CURRENT_TIMESTAMP ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1");if(!$row)return null;DB::statement("UPDATE document_jobs SET status='processing',attempts=attempts+1,started_at=CURRENT_TIMESTAMP,error_message=NULL WHERE id=?",[$row->id]);DB::statement("UPDATE contracts SET pdf_status='processing',pdf_error_message=NULL WHERE id=?",[$row->contract_id]);$row->attempts=(int)$row->attempts+1;return$row;});}
    private function process(object $job):void
    {
        $c=DB::selectOne('SELECT c.id AS contract_id,cv.id AS contract_version_id,c.serial_number,c.user_id,c.client_user_id,c.issued_at,c.variant_key,c.selected_optional_clause_keys,c.field_values_json,cv.legal_clause_snapshot_json,tv.definition_json FROM contracts c JOIN contract_versions cv ON cv.id=? AND cv.contract_id=c.id JOIN template_versions tv ON tv.id=c.template_version_id WHERE c.id=? AND c.deleted_at IS NULL',[$job->contract_version_id,$job->contract_id]);if(!$c)throw new \RuntimeException('Contract/version/template context was not found');$definition=$this->json($c->definition_json);$fields=$this->json($c->field_values_json);$clauses=$this->list($c->legal_clause_snapshot_json);$optionalKeys=$this->list($c->selected_optional_clause_keys);$variant=collect($definition['variants']??[])->firstWhere('key',$c->variant_key);if(!$variant)throw new \RuntimeException("Template variant {$c->variant_key} is missing");
        $folder=$this->safe($c->serial_number).'/v'.$c->contract_version_id;$separate=[];foreach($definition['optionalClauses']??[]as$optional)if(in_array($optional['key']??'', $optionalKeys,true)&&($optional['outputMode']??null)==='separate_annex')foreach($optional['legalClauseKeys']??[]as$key)$separate[(string)$key]=true;
        $mainClauses=array_values(array_filter($clauses,fn($clause)=>!isset($separate[$clause['key']??''])));$mainKey=$folder.'/'.$this->safe($c->serial_number).'.pdf';$main=$this->generate($mainKey,$this->render($definition,$variant,$optionalKeys,$fields,$mainClauses,'main',null,$c));$this->persist($c,'main','main',null,$variant['documentTitleAr']??$variant['nameAr'],$mainKey,$main);
        foreach($optionalKeys as$key){$optional=collect($definition['optionalClauses']??[])->first(fn($x)=>($x['key']??null)===$key&&($x['outputMode']??null)==='separate_annex');if(!$optional)continue;$keys=array_fill_keys($optional['legalClauseKeys']??[],true);$annexClauses=array_values(array_filter($clauses,fn($clause)=>isset($keys[$clause['key']??''])));$annexKey=$folder.'/'.$this->safe($c->serial_number).'-'.$this->safe($key).'.pdf';$annex=$this->generate($annexKey,$this->render($definition,$variant,$optionalKeys,$fields,$annexClauses,'annex',$key,$c));$this->persist($c,'annex:'.$key,'annex',$key,$optional['documentTitleAr']??$optional['nameAr'],$annexKey,$annex);}
        DB::transaction(function()use($job,$c,$main){DB::statement('UPDATE contract_versions SET pdf_path=? WHERE id=? AND contract_id=?',[$main['path'],$c->contract_version_id,$c->contract_id]);DB::statement("UPDATE contracts SET pdf_path=?,pdf_status='ready',pdf_error_message=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$main['path'],$c->contract_id]);DB::statement("UPDATE document_jobs SET status='completed',completed_at=CURRENT_TIMESTAMP,error_message=NULL WHERE id=?",[$job->id]);$this->notifications->notify((int)($c->client_user_id??$c->user_id),'contract_pdf_ready','عقدك النهائي جاهز للتحميل',"{$c->serial_number}: تم تجهيز ملف PDF النهائي والملاحق المختارة","/contract/{$c->contract_id}",['contractId'=>$c->contract_id,'contractVersionId'=>$c->contract_version_id]);});
    }
    private function render(array $definition,array $variant,array $optionalKeys,array $fields,array $clauses,string $kind,?string $optionalKey,object $c):string
    {
        $steps=$kind==='main'?($variant['steps']??[]):[];$title=$variant['documentTitleAr']??$variant['nameAr']??'عقد';if($kind==='annex'){$optional=collect($definition['optionalClauses']??[])->firstWhere('key',$optionalKey);$steps=$optional['insertedSteps']??[];$title=$optional['documentTitleAr']??$optional['nameAr']??'ملحق';}
        $sections=[];foreach($steps as$step){$rows=[];foreach($step['fields']??[]as$field){$key=(string)($field['key']??'');$value=$fields[$key]??null;if($this->empty($value))continue;$rows[]=['label'=>$field['labelAr']??$key,'value'=>$this->display($value,$field)];}$sections[]=['title'=>$step['titleAr']??'البيانات','rows'=>$rows];}
        $office=DB::selectOne("SELECT setting_value_json #>> '{}' AS value FROM platform_settings WHERE setting_key='office.display_name'");$logo=resource_path('zdraft-logo-transparent.png');$logoPath=is_file($logo)?'file://'.$logo:null;
        return view('pdf.contract',['officeName'=>$office->value??'Z draft Law Office','logoPath'=>$logoPath,'title'=>$title,'serialNumber'=>$c->serial_number,'issuedAt'=>$c->issued_at?date('Y-m-d',strtotime((string)$c->issued_at)):date('Y-m-d'),'documentKind'=>$kind,'sections'=>$sections,'clauses'=>$clauses])->render();
    }
    private function generate(string $key,string $html):array
    {
        $path=Storage::disk('contracts')->path($key);if(!is_dir(dirname($path))&&!mkdir(dirname($path),0770,true)&&!is_dir(dirname($path)))throw new \RuntimeException('Cannot create PDF directory');$temp=tempnam(storage_path('framework'),'zdraft-html-');if($temp===false)throw new \RuntimeException('Cannot create temporary HTML');file_put_contents($temp,$html);try{$process=new Process([config('zdraft.weasyprint_binary'),$temp,$path]);$process->setTimeout(config('zdraft.pdf_timeout_seconds'));$process->run();if(!$process->isSuccessful())throw new \RuntimeException('WeasyPrint failed: '.$process->getErrorOutput().' '.$process->getOutput());if(!is_file($path)||filesize($path)<500)throw new \RuntimeException('Generated PDF is missing or invalid');return['path'=>$path,'sha256'=>hash_file('sha256',$path),'sizeBytes'=>filesize($path)];}finally{@unlink($temp);}
    }
    private function persist(object $c,string $fileKey,string $type,?string $optional,string $title,string $storageKey,array $file):void{DB::statement("INSERT INTO contract_document_files(contract_id,contract_version_id,file_key,document_type,optional_clause_key,title_ar,storage_path,storage_driver,storage_key,sha256,file_size_bytes) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (contract_version_id,file_key) DO UPDATE SET document_type=EXCLUDED.document_type,optional_clause_key=EXCLUDED.optional_clause_key,title_ar=EXCLUDED.title_ar,storage_path=EXCLUDED.storage_path,storage_driver=EXCLUDED.storage_driver,storage_key=EXCLUDED.storage_key,sha256=EXCLUDED.sha256,file_size_bytes=EXCLUDED.file_size_bytes,updated_at=CURRENT_TIMESTAMP",[$c->contract_id,$c->contract_version_id,$fileKey,$type,$optional,$title,$file['path'],'local',$storageKey,$file['sha256'],$file['sizeBytes']]);}
    private function markFailed(object $job,\Throwable $e):void{$message=mb_substr($e->getMessage()."\n".$e->getTraceAsString(),0,5000);$terminal=(int)$job->attempts>=5;$delay=min(30,2**max(1,(int)$job->attempts));DB::transaction(function()use($job,$message,$terminal,$delay){DB::statement("UPDATE document_jobs SET status=?,error_message=?,available_at=CURRENT_TIMESTAMP+(?::text || ' minutes')::interval WHERE id=?",[$terminal?'failed':'retry',$message,$delay,$job->id]);DB::statement('UPDATE contracts SET pdf_status=?,pdf_error_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[$terminal?'failed':'queued',mb_substr($message,0,2000),$job->contract_id]);});}
    private function display(mixed $value,array $field):string{if(is_bool($value))return$value?'نعم':'لا';if(is_array($value)){if(array_is_list($value)&&isset($field['options'])){$labels=[];foreach($value as$v){$o=collect($field['options'])->firstWhere('value',$v);$labels[]=$o['labelAr']??(string)$v;}return implode('، ',$labels);}return collect($value)->map(function($row,$i){if(!is_array($row))return(string)$row;return($i+1).') '.implode(' | ',array_map(fn($k,$v)=>$k.': '.$v,array_keys($row),$row));})->implode("\n");}$option=collect($field['options']??[])->firstWhere('value',$value);return(string)($option['labelAr']??$value);}
    private function json(mixed $v):array{if(is_array($v))return$v;if(is_object($v))return(array)$v;if(is_string($v))return json_decode($v,true)?:[];return[];}private function list(mixed $v):array{return array_values($this->json($v));}private function empty(mixed$v):bool{return$v===null||$v===''||(is_array($v)&&!count($v));}private function safe(string$v):string{return trim(preg_replace('/[^A-Za-z0-9._-]+/','-',$v),'-')?:'document';}
}
