"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Bell, CheckCheck, RefreshCw } from "lucide-react";
import { dashboardRequest } from "@/lib/apiClient";
import { PageError, PageLoading } from "@/components/admin/PageFeedback";

type Notice={id:number;type:string;title:string;message:string;actionUrl?:string;readAt?:string;createdAt:string};
export default function NotificationsPage(){const [items,setItems]=useState<Notice[]>([]),[unread,setUnread]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await dashboardRequest<{items:Notice[];unreadCount:number}>("/api/v1/notifications");setItems(r.items);setUnread(r.unreadCount);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الإشعارات");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);async function read(id:number){await dashboardRequest(`/api/v1/notifications/${id}/read`,{method:"PATCH"});await load();}async function readAll(){await dashboardRequest("/api/v1/notifications/read-all",{method:"PATCH"});await load();}if(loading&&!items.length)return <div className="p-8"><PageLoading/></div>;if(error&&!items.length)return <div className="p-8"><PageError message={error} onRetry={load}/></div>;return <div className="mx-auto max-w-5xl space-y-6 p-6 sm:p-8"><header className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black text-[#00102e]">الإشعارات</h1><p className="text-sm text-slate-500">{unread} إشعار غير مقروء.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>void readAll()} className="inline-flex items-center gap-2 rounded-xl bg-[#00102e] px-4 py-2.5 text-xs font-black text-[#d5a84c]"><CheckCheck className="h-4 w-4"/>تعليم الكل كمقروء</button></div></header><div className="space-y-3">{items.map(n=><article key={n.id} className={`rounded-2xl border p-5 ${n.readAt?"border-slate-200 bg-white":"border-[#986410]/30 bg-[#986410]/5"}`}><div className="flex items-start gap-3"><div className="rounded-xl bg-[#00102e] p-2 text-[#d5a84c]"><Bell className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-black text-[#00102e]">{n.title}</h2><time className="text-[10px] text-slate-400">{new Date(n.createdAt).toLocaleString("ar-EG")}</time></div><p className="mt-2 text-sm leading-6 text-slate-600">{n.message}</p><div className="mt-3 flex gap-2">{n.actionUrl&&<Link href={n.actionUrl} className="rounded-lg bg-[#00102e] px-3 py-2 text-xs font-black text-white">فتح الإجراء</Link>}{!n.readAt&&<button onClick={()=>void read(n.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black">تمت القراءة</button>}</div></div></div></article>)}{items.length===0&&<div className="rounded-2xl border border-slate-200 bg-white p-12 text-center text-sm font-bold text-slate-500">لا توجد إشعارات.</div>}</div></div>}
