<?php
return [
    'frontend_url' => env('FRONTEND_URL', 'http://localhost:3000'),
    'dashboard_url' => env('DASHBOARD_URL', 'http://localhost:3001'),
    'cors_extra_origins' => array_values(array_filter(array_map('trim', explode(',', (string) env('CORS_EXTRA_ORIGINS', env('CORS_EXTRA_ORIGIN', '')))))),
    'frontend_session_cookie' => env('ZDRAFT_FRONTEND_SESSION_COOKIE', env('ZDRAFT_SESSION_COOKIE', 'zdraft_user_session')),
    'frontend_csrf_cookie' => env('ZDRAFT_FRONTEND_CSRF_COOKIE', env('ZDRAFT_CSRF_COOKIE', 'zdraft_user_csrf')),
    'dashboard_session_cookie' => env('ZDRAFT_DASHBOARD_SESSION_COOKIE', 'zdraft_admin_session'),
    'dashboard_csrf_cookie' => env('ZDRAFT_DASHBOARD_CSRF_COOKIE', 'zdraft_admin_csrf'),
    'cookie_domain' => env('COOKIE_DOMAIN'),
    'cookie_same_site' => env('COOKIE_SAME_SITE', 'lax'),
    'cookie_secure' => filter_var(env('COOKIE_SECURE', env('APP_ENV', 'production') === 'production'), FILTER_VALIDATE_BOOL),
    'session_ttl_hours' => (int) env('SESSION_TTL_HOURS', 168),
    'otp_ttl_minutes' => (int) env('EMAIL_OTP_TTL_MINUTES', 10),
    'otp_max_attempts' => (int) env('EMAIL_OTP_MAX_ATTEMPTS', 5),
    'otp_resend_cooldown_seconds' => (int) env('EMAIL_OTP_RESEND_COOLDOWN_SECONDS', 60),
    'password_reset_ttl_minutes' => (int) env('PASSWORD_RESET_TTL_MINUTES', 30),
    'expose_debug_tokens' => filter_var(env('EXPOSE_DEBUG_TOKENS', false), FILTER_VALIDATE_BOOL),
    'image' => [
        'max_dimension' => (int) env('IMAGE_MAX_DIMENSION', 1920),
        'max_input_pixels' => (int) env('IMAGE_MAX_INPUT_PIXELS', 40000000),
        'max_bytes' => (int) env('IMAGE_MAX_BYTES', 1572864),
        'thumbnail_dimension' => (int) env('IMAGE_THUMBNAIL_DIMENSION', 480),
        'webp_quality' => (int) env('IMAGE_WEBP_QUALITY', 84),
        'webp_effort' => (int) env('IMAGE_WEBP_EFFORT', 6),
        'thumbnail_quality' => (int) env('IMAGE_THUMBNAIL_QUALITY', 72),
        'preserve_original' => filter_var(env('IMAGE_PRESERVE_ORIGINAL', false), FILTER_VALIDATE_BOOL),
    ],
    'clamav' => ['enabled' => filter_var(env('CLAMAV_ENABLED', false), FILTER_VALIDATE_BOOL), 'binary' => env('CLAMAV_BINARY', 'clamscan')],
    'weasyprint_binary' => env('WEASYPRINT_BINARY', '/usr/bin/weasyprint'),
    'pdf_timeout_seconds' => (int) env('PDF_TIMEOUT_SECONDS', 120),
    'features' => [
        'team_management' => filter_var(env('FEATURE_TEAM_MANAGEMENT', false), FILTER_VALIDATE_BOOL),
        'assignment' => filter_var(env('FEATURE_ASSIGNMENT', false), FILTER_VALIDATE_BOOL),
        'office_contract_creation' => filter_var(env('FEATURE_OFFICE_CONTRACT_CREATION', false), FILTER_VALIDATE_BOOL),
        'contract_editing' => filter_var(env('FEATURE_CONTRACT_EDITING', false), FILTER_VALIDATE_BOOL),
        'template_management' => filter_var(env('FEATURE_TEMPLATE_MANAGEMENT', false), FILTER_VALIDATE_BOOL),
    ],
];
