"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Plus, RefreshCw, ShieldCheck, UserX } from "lucide-react";
import { dashboardRequest } from "@/lib/apiClient";
import { PageError, PageLoading, StatusBadge } from "@/components/admin/PageFeedback";

type Member={id:number;publicId:string;name:string;email:string;phone?:string;status:string;staffStatus:string;jobTitle?:string;lastLoginAt?:string;roles:string[]};
type Role={id:number;roleKey:string;nameAr:string;permissions:Array<{key:string;nameAr:string}>};
export default function TeamPage(){
 const [members,setMembers]=useState<Member[]>([]),[roles,setRoles]=useState<Role[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[tempPassword,setTempPassword]=useState("");
 const load=useCallback(async()=>{setError("");try{const [m,r]=await Promise.all([dashboardRequest<Member[]>("/api/v1/admin/team"),dashboardRequest<Role[]>("/api/v1/admin/team/roles")]);setMembers(m);setRoles(r);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الفريق");}},[]);useEffect(()=>{void load();},[load]);
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);try{const result=await dashboardRequest<{userId:number;temporaryPassword?:string}>("/api/v1/admin/team/invite",{method:"POST",body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),jobTitle:fd.get("jobTitle"),roleKey:fd.get("roleKey")})});setTempPassword(result.temporaryPassword||"");setOpen(false);await load();}catch(x){setError(x instanceof Error?x.message:"تعذر إرسال الدعوة");}finally{setBusy(false);}}
 async function updateStatus(m:Member){setBusy(true);try{await dashboardRequest(`/api/v1/admin/team/${m.id}/status`,{method:"PATCH",body:JSON.stringify({status:m.status==="suspended"?"active":"suspended"})});await load();}catch(x){setError(x instanceof Error?x.message:"تعذر تحديث الحساب");}finally{setBusy(false);}}
 async function updateRole(id:number,roleKey:string){if(!roleKey)return;setBusy(true);try{await dashboardRequest(`/api/v1/admin/team/${id}/roles`,{method:"PATCH",body:JSON.stringify({roleKeys:[roleKey]})});await load();}catch(x){setError(x instanceof Error?x.message:"تعذر تحديث الدور");}finally{setBusy(false);}}
 if(error&&!members.length)return <div className="p-8"><PageError message={error} onRetry={load}/></div>;if(!members.length&&!error&&!roles.length)return <div className="p-8"><PageLoading/></div>;
 return <div className="mx-auto max-w-7xl space-y-6 p-6 sm:p-8"><header className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black text-[#00102e]">الفريق والصلاحيات</h1><p className="text-sm text-slate-500">حساب مستقل لكل محامٍ أو موظف. لا توجد كلمة مرور مشتركة للمكتب.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#00102e] px-5 py-3 text-xs font-black text-[#d5a84c]"><Plus className="h-4 w-4"/>دعوة عضو</button></div></header>{error&&<div className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}{tempPassword&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs font-bold text-amber-900">كلمة المرور المؤقتة في بيئة التطوير: <code className="font-mono">{tempPassword}</code> — لا تظهر في الإنتاج.</div>}
 <div className="grid gap-4 lg:grid-cols-2">{members.map(m=><article key={m.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><div className="font-black text-[#00102e]">{m.name}</div><div className="mt-1 text-xs text-slate-500">{m.email} · {m.jobTitle||"بدون مسمى وظيفي"}</div><div className="mt-2 font-mono text-[10px] text-slate-400">{m.publicId}</div></div><StatusBadge value={m.status}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-black text-slate-500">الدور<select disabled={busy} value={m.roles[0]||""} onChange={e=>void updateRole(m.id,e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-xs text-slate-700"><option value="">اختر الدور</option>{roles.map(r=><option key={r.id} value={r.roleKey}>{r.nameAr}</option>)}</select></label><div className="text-[11px] font-black text-slate-500">آخر دخول<div className="mt-1 rounded-xl bg-slate-50 p-2.5 text-xs text-slate-700">{m.lastLoginAt?new Date(m.lastLoginAt).toLocaleString("ar-EG"):"لم يدخل بعد"}</div></div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><div className="flex items-center gap-1 text-[10px] font-bold text-slate-400"><ShieldCheck className="h-3.5 w-3.5"/>{m.roles.join("، ")||"بدون دور"}</div><button disabled={busy} onClick={()=>void updateStatus(m)} className={`inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-black ${m.status==="suspended"?"bg-emerald-700 text-white":"bg-red-50 text-red-700"}`}><UserX className="h-3.5 w-3.5"/>{m.status==="suspended"?"إعادة التفعيل":"تعليق الحساب"}</button></div></article>)}</div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={()=>setOpen(false)}><form onSubmit={invite} onClick={e=>e.stopPropagation()} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6"><h2 className="text-xl font-black text-[#00102e]">دعوة عضو جديد</h2><input name="name" required placeholder="الاسم الكامل" className="w-full rounded-xl border border-slate-200 p-3"/><input name="email" type="email" required placeholder="البريد الإلكتروني" className="w-full rounded-xl border border-slate-200 p-3"/><input name="jobTitle" placeholder="المسمى الوظيفي" className="w-full rounded-xl border border-slate-200 p-3"/><select name="roleKey" required className="w-full rounded-xl border border-slate-200 p-3"><option value="">اختر الدور</option>{roles.map(r=><option key={r.id} value={r.roleKey}>{r.nameAr}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black">إلغاء</button><button disabled={busy} className="rounded-xl bg-[#00102e] px-5 py-2 text-xs font-black text-[#d5a84c]">إرسال الدعوة</button></div></form></div>}
 </div>;
}
