"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, RefreshCw, ShieldCheck, ShieldX } from "lucide-react";
import { dashboardRequest } from "@/lib/apiClient";
import { PageError, PageLoading } from "@/components/admin/PageFeedback";

type Audit={id:number;requestId:string;action:string;entityType:string;entityId:string;oldValues?:unknown;newValues?:unknown;ipAddress?:string;recordHash:string;createdAt:string;actorName?:string;actorEmail?:string};
type AuditResponse={items:Audit[];pagination:{page:number;perPage:number;total:number;pages:number}};
type Verify={valid:boolean;checked:number;total:number;fullyVerified?:number;legacyUnverifiable?:number;firstBroken?:{id:number;reason:string}|null};
const labels:Record<string,string>={
  "auth.login":"تسجيل دخول","auth.registered":"إنشاء حساب","auth.email_verified":"تأكيد البريد","auth.password_changed":"تغيير كلمة المرور",
  "contract.draft_created":"إنشاء مسودة عقد","contract.draft_updated":"تعديل مسودة عقد","contract.version_created":"إنشاء إصدار عقد","contract.version_updated":"تعديل إصدار عقد","contract.status_changed":"تغيير حالة عقد","contract.locked":"قفل عقد","contract.issued":"إصدار عقد","contract.share_created":"إنشاء مشاركة عقد","contract.share_revoked":"إلغاء مشاركة عقد","contract.payment_waived":"إعفاء عقد من الدفع",
  "payment.receipt_uploaded":"رفع إيصال دفع","payment.approved":"اعتماد دفع","payment.rejected":"رفض دفع","payment.clarification_requested":"طلب توضيح دفع","payment.manual_recorded":"تسجيل تحصيل يدوي",
  "user.status_changed":"تغيير حالة عميل","settings.updated":"تعديل الإعدادات","consultation.schedule_updated":"تعديل جدول الاستشارات","consultation.schedule_blocked":"حظر موعد استشارة",
};
const entityLabels:Record<string,string>={user:"مستخدم",contract:"عقد",payment:"دفع",service_request:"طلب خدمة",contract_version:"إصدار عقد",contract_share:"مشاركة عقد",consultation_schedule:"جدول الاستشارات",consultation_schedule_exception:"استثناء موعد",platform_settings:"إعدادات"};

export default function AuditPage(){
  const [items,setItems]=useState<Audit[]>([]),[entity,setEntity]=useState(""),[mode,setMode]=useState<"business"|"security"|"all">("business"),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[verify,setVerify]=useState<Verify|null>(null),[verifying,setVerifying]=useState(false),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);
  const load=useCallback(async()=>{setError("");try{const q=new URLSearchParams({page:String(page),perPage:"50"});if(entity)q.set("entityType",entity);if(from)q.set("from",from);if(to)q.set("to",to);const result=await dashboardRequest<AuditResponse>(`/api/v1/admin/audit?${q.toString()}`);setItems(result.items);setPages(Math.max(1,result.pagination.pages));setTotal(result.pagination.total);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل السجل");}finally{setLoaded(true);}},[entity,from,to,page]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>setPage(1),[entity,from,to]);
  const visible=useMemo(()=>items.filter(item=>mode==="all"||(mode==="security"?item.action.startsWith("auth."):!item.action.startsWith("auth."))),[items,mode]);
  async function verifyChain(){setVerifying(true);setError("");try{setVerify(await dashboardRequest<Verify>("/api/v1/admin/audit/verify"));}catch(e){setError(e instanceof Error?e.message:"تعذر فحص سلامة السجل");}finally{setVerifying(false);}}
  if(!loaded)return <div className="p-8"><PageLoading/></div>;if(error&&!items.length)return <div className="p-8"><PageError message={error} onRetry={load}/></div>;
  return <div className="mx-auto max-w-7xl space-y-6 p-6 sm:p-8">
    <header className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black text-[#00102e]">الأمان وسجل النظام</h1><p className="text-sm text-slate-500">مرجع عند الحاجة لمعرفة من قام بإجراء حساس ومتى. ليس جزءًا من التشغيل اليومي.</p></div><div className="flex flex-wrap gap-2"><button disabled={verifying} onClick={()=>void verifyChain()} className="inline-flex items-center gap-2 rounded-xl bg-[#00102e] px-4 py-2.5 text-xs font-black text-white"><ShieldCheck className="h-4 w-4 text-[#986410]"/>{verifying?"جاري الفحص...":"تحقق من سلامة السجل"}</button><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-2.5" aria-label="تحديث"><RefreshCw className="h-4 w-4"/></button></div></header>
    {error&&<div className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}{verify&&<div className={`flex items-start gap-3 rounded-xl border p-4 text-xs font-black ${verify.valid?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`}>{verify.valid?<CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0"/>:<ShieldX className="mt-0.5 h-5 w-5 shrink-0"/>}<div>{verify.valid?`سلسلة الربط سليمة — تم فحص ${verify.checked} سجل.`:`يوجد عدم تطابق عند السجل #${verify.firstBroken?.id??"—"}.`}{verify.valid&&Boolean(verify.legacyUnverifiable)&&<div className="mt-1 text-[10px] font-bold text-emerald-700/80">تم التحقق الكامل من {verify.fullyVerified??0} سجل حديث، و{verify.legacyUnverifiable} سجل قديم تم التحقق من ترابطه فقط لأن صيغة البصمة القديمة لم تكن تحفظ ترتيب JSON.</div>}</div></div>}
    <div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="flex rounded-xl bg-slate-100 p-1">{[["business","عمليات العمل"],["security","الأمان وتسجيل الدخول"],["all","الكل"]].map(([value,label])=><button key={value} onClick={()=>setMode(value as typeof mode)} className={`rounded-lg px-3 py-2 text-[10px] font-black ${mode===value?"bg-white text-[#00102e] shadow-sm":"text-slate-500"}`}>{label}</button>)}</div><select value={entity} onChange={e=>setEntity(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold"><option value="">كل الكيانات</option><option value="contract">العقود</option><option value="payment">المدفوعات</option><option value="service_request">طلبات الخدمات</option><option value="user">المستخدمون</option><option value="platform_settings">الإعدادات</option></select><label className="flex items-center gap-2 text-[10px] font-black text-slate-500">من<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"/></label><label className="flex items-center gap-2 text-[10px] font-black text-slate-500">إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"/></label></div><div className="text-[10px] font-bold text-slate-400">إجمالي النتائج المطابقة: {total.toLocaleString("ar-EG")}</div></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-right text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">الوقت</th><th className="p-4">الفاعل</th><th className="p-4">الفعل</th><th className="p-4">الكيان</th><th className="p-4">التغيير</th><th className="p-4">البصمة</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(item=><tr key={item.id} className="align-top"><td className="whitespace-nowrap p-4">{new Date(item.createdAt).toLocaleString("ar-EG")}</td><td className="p-4"><div className="font-black">{item.actorName||"النظام"}</div><div className="text-[10px] text-slate-400">{item.actorEmail||item.ipAddress||"—"}</div></td><td className="p-4"><div className="font-black text-[#00102e]">{labels[item.action]||item.action}</div><div className="mt-1 font-mono text-[9px] text-slate-400">{item.action}</div></td><td className="p-4">{entityLabels[item.entityType]||item.entityType} #{item.entityId}</td><td className="p-4"><Diff oldValue={item.oldValues} newValue={item.newValues}/></td><td className="p-4"><div className="flex items-center gap-1 text-emerald-700"><ShieldCheck className="h-4 w-4"/><span className="font-mono text-[9px]">{item.recordHash.slice(0,18)}…</span></div></td></tr>)}</tbody></table></div>{visible.length===0&&<div className="p-12 text-center text-sm font-bold text-slate-500">لا توجد نتائج في هذا التصنيف.</div>}<div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-[10px] font-black text-slate-500"><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40"><ChevronLeft className="h-3 w-3 rotate-180"/>السابق</button><span>صفحة {page.toLocaleString("ar-EG")} من {pages.toLocaleString("ar-EG")}</span><button disabled={page>=pages} onClick={()=>setPage(v=>Math.min(pages,v+1))} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40">التالي<ChevronLeft className="h-3 w-3"/></button></div></div>
  </div>;
}

function Diff({oldValue,newValue}:{oldValue?:unknown;newValue?:unknown}){const oldObj=(oldValue&&typeof oldValue==="object"?oldValue:{}) as Record<string,unknown>;const newObj=(newValue&&typeof newValue==="object"?newValue:{}) as Record<string,unknown>;const keys=Array.from(new Set([...Object.keys(oldObj),...Object.keys(newObj)]));if(!keys.length)return <span className="text-slate-400">—</span>;return <details><summary className="cursor-pointer font-black text-blue-700">عرض التغييرات ({keys.length})</summary><div className="mt-2 max-w-md space-y-1 rounded-lg bg-slate-50 p-3">{keys.slice(0,12).map(key=><div key={key} className="grid grid-cols-[110px_1fr] gap-2 text-[9px]"><b className="truncate text-slate-500">{key}</b><span className="break-all text-slate-700">{format(oldObj[key])} → {format(newObj[key])}</span></div>)}{keys.length>12&&<div className="text-[9px] text-slate-400">+ {keys.length-12} حقول أخرى</div>}</div></details>;}
function format(value:unknown){if(value===undefined||value===null||value==="")return"—";if(typeof value==="object")return JSON.stringify(value);return String(value);}
