<?php
namespace App\Http\Controllers;

use App\Exceptions\ApiException;
use App\Services\AuditService;
use App\Services\NotificationService;
use App\Services\PrivateStorageService;
use App\Services\TemplateEngineService;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

final class ContractController extends Controller
{
    use ApiResponse;
    public function __construct(private TemplateEngineService $engine,private NotificationService $notifications,private AuditService $audit,private PrivateStorageService $storage){}

    public function sharedInfo(Request $request,string $token){$s=$this->loadShare($token);return$this->ok($request,['contractTitle'=>$s->title,'serialNumber'=>$s->serial_number,'templateSlug'=>$s->template_slug,'permission'=>$s->permission_level,'ownerName'=>$this->maskName($s->owner_name),'expiresAt'=>$s->expires_at,'requiresPublicId'=>(bool)$s->target_public_id]);}
    public function sharedAccess(Request $request,string $token){$s=$this->loadShare($token);$data=$request->validate(['publicId'=>['nullable','string','max:40']]);$publicId=strtoupper($data['publicId']??'');if($s->target_public_id&&strtoupper($s->target_public_id)!==$publicId)throw new ApiException(403,'Z-ID غير مطابق للدعوة','SHARE_ID_MISMATCH');return$this->ok($request,['contractId'=>(int)$s->contract_id,'contractTitle'=>$s->title,'serialNumber'=>$s->serial_number,'templateSlug'=>$s->template_slug,'variantKey'=>$s->variant_key,'permission'=>$s->permission_level,'ownerName'=>$this->maskName($s->owner_name),'expiresAt'=>$s->expires_at,'fieldValues'=>$this->json($s->field_values_json),'selectedOptionalClauseKeys'=>$this->jsonList($s->selected_optional_clause_keys),'editableFieldKeys'=>$this->jsonList($s->editable_field_keys)]);}
    public function sharedUpdate(Request $request,string $token)
    {
        $s=$this->loadShare($token);if($s->permission_level!=='edit')throw new ApiException(403,'الرابط للعرض فقط');if(!in_array($s->status,['draft','revision_requested','client_review'],true))throw new ApiException(409,'العقد لا يقبل تعديلات مشاركة في حالته الحالية');$data=$request->validate(['publicId'=>['nullable','string','max:40'],'fieldValues'=>['required','array']]);$publicId=strtoupper($data['publicId']??'');if($s->target_public_id&&strtoupper($s->target_public_id)!==$publicId)throw new ApiException(403,'Z-ID غير مطابق للدعوة');$editable=array_fill_keys($this->jsonList($s->editable_field_keys),true);$unauthorized=array_values(array_filter(array_keys($data['fieldValues']),fn($key)=>!isset($editable[$key])));if($unauthorized)throw new ApiException(403,'تتضمن التعديلات حقولًا غير مسموح بها','SHARE_FIELDS_FORBIDDEN',$unauthorized);
        $definition=$this->json($s->template_definition);$current=$this->json($s->field_values_json);$optional=$this->jsonList($s->selected_optional_clause_keys);$window=$this->editWindow($s->edit_expires_at);if($s->status==='client_review'&&!$window['active'])throw new ApiException(409,'انتهت مهلة التعديل لهذا العقد','EDIT_WINDOW_EXPIRED');if($s->core_identity_locked){$core=array_fill_keys($this->engine->coreIdentityFieldKeys($definition,$s->variant_key),true);$changes=array_values(array_filter(array_keys($data['fieldValues']),fn($key)=>isset($core[$key])));if($changes)throw new ApiException(409,'لا يمكن تعديل بيانات الأطراف أو محل العقد بعد اعتماد الدفع','CORE_IDENTITY_LOCKED',$changes);}
        $merged=array_merge($current,$data['fieldValues']);$validation=$this->engine->validateDraft($definition,$s->variant_key,$optional,$merged,$this->json($s->attachment_refs_json));$status=$s->status==='client_review'?'client_review':'revision_requested';
        DB::transaction(function()use($request,$s,$merged,$status,$data){DB::statement('UPDATE contracts SET field_values_json=?::jsonb,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[json_encode($merged,JSON_UNESCAPED_UNICODE),$status,$s->contract_id]);DB::statement('UPDATE contract_versions SET field_values_json=?::jsonb,status=? WHERE id=(SELECT current_version_id FROM contracts WHERE id=?)',[json_encode($merged,JSON_UNESCAPED_UNICODE),$status,$s->contract_id]);$this->notifications->notify((int)($s->client_user_id??$s->user_id),'contract_shared_update','تم تعديل بيانات من رابط المشاركة',"{$s->serial_number}: توجد تعديلات تحتاج مراجعتك","/contract/{$s->contract_id}");$this->audit->write($request,'contract.shared_fields_updated','contract',(int)$s->contract_id,$this->json($s->field_values_json),$data['fieldValues'],null);});
        return$this->ok($request,['contractId'=>(int)$s->contract_id,'status'=>$status,'issues'=>$validation['issues']],'تم حفظ التعديلات وإشعار صاحب العقد');
    }

    public function createDraft(Request $request)
    {
        $auth=$this->auth($request);$this->verified($auth);$data=$request->validate(['templateSlug'=>['nullable','string','max:100'],'slug'=>['nullable','string','max:100'],'variantKey'=>['nullable','string','max:140'],'selectedOptionalClauseKeys'=>['nullable','array'],'fieldValues'=>['nullable','array'],'formData'=>['nullable','array'],'attachmentRefs'=>['nullable','array'],'currentStepKey'=>['nullable','string','max:140'],'sourceChannel'=>['nullable','in:customer,office'],'creationMode'=>['nullable','in:self_service,lawyer_assisted,office_assisted'],'mode'=>['nullable','in:self_service,lawyer_assisted,office_assisted'],'officeContext'=>['nullable','array']]);
        $slug=$data['templateSlug']??$data['slug']??null;if(!$slug)throw new ApiException(400,'templateSlug مطلوب');$source=$data['sourceChannel']??(in_array($data['creationMode']??$data['mode']??'', ['office_assisted'],true)?'office':'customer');$mode=$data['creationMode']??$data['mode']??'self_service';if($source==='office'&&!config('zdraft.features.office_contract_creation'))throw new ApiException(404,'إنشاء العقود من لوحة التحكم مخفي حاليًا','FEATURE_DISABLED');
        $template=$this->publishedTemplate($slug);$definition=$template['definition'];$variantKey=$data['variantKey']??(count($definition['variants']??[])===1?($definition['variants'][0]['key']??null):null);if(!$variantKey)throw new ApiException(400,'يجب اختيار نوع العقد');$optional=array_values(array_map('strval',$data['selectedOptionalClauseKeys']??[]));$fields=$data['fieldValues']??$data['formData']??[];$attachments=$data['attachmentRefs']??[];$validation=$this->engine->validateDraft($definition,$variantKey,$optional,$fields,$attachments);
        $variant=collect($definition['variants']??[])->firstWhere('key',$variantKey);$clientId=$source==='customer'?$auth['id']:null;$owner=$clientId??$auth['id'];$office=$data['officeContext']??null;$billing='client_invoice';$waiver=null;$assigned=null;if($source==='office'){if(!$office)throw new ApiException(400,'بيانات إنشاء العقد من المكتب مطلوبة');$billing=$office['billingMode']??'client_invoice';$waiver=$office['waiverReason']??null;if(($office['clientMode']??null)==='existing')$clientId=(int)($office['clientId']??0);$owner=$clientId?:$auth['id'];$assigned=!empty($office['assignedLawyerId'])?(int)$office['assignedLawyerId']:null;}
        $serial=$this->serial($slug);$result=DB::transaction(function()use($request,$auth,$data,$template,$definition,$variant,$variantKey,$optional,$fields,$attachments,$source,$mode,$clientId,$owner,$office,$billing,$waiver,$assigned,$serial){$row=DB::selectOne("INSERT INTO contracts(serial_number,user_id,client_user_id,created_by_user_id,template_id,template_version_id,creation_mode,source_channel,status,core_identity_locked,template_version,variant_key,selected_optional_clause_keys,field_values_json,attachment_refs_json,current_step_key,title,billing_mode,original_price_egp,waiver_reason,assigned_lawyer_id) VALUES (?,?,?,?,?,?,?,?,'draft',FALSE,?,?,?::jsonb,?::jsonb,?::jsonb,?,?,?,?,?,?) RETURNING id",[$serial,$owner,$clientId,$auth['id'],$template['templateId'],$template['versionId'],$mode,$source,$definition['version'],$variantKey,json_encode($optional),json_encode($fields,JSON_UNESCAPED_UNICODE),json_encode($attachments,JSON_UNESCAPED_UNICODE),$data['currentStepKey']??($variant['steps'][0]['key']??'start'),$variant['documentTitleAr']??$variant['nameAr'],$billing,$definition['priceEgp']??0,$waiver,$assigned]);$id=(int)$row->id;$this->linkContractAttachments($attachments,$auth['id'],$id);$ver=DB::selectOne("INSERT INTO contract_versions(contract_id,version_number,template_version,template_version_id,variant_key,selected_optional_clause_keys,field_values_json,legal_clause_snapshot_json,status,created_by) VALUES (?,1,?,?,?,?,?::jsonb,'[]'::jsonb,'draft',?) RETURNING id",[$id,$definition['version'],$template['versionId'],$variantKey,json_encode($optional),json_encode($fields,JSON_UNESCAPED_UNICODE),$auth['id']]);DB::table('contracts')->where('id',$id)->update(['current_version_id'=>$ver->id]);if($source==='office'&&$office)DB::insert('INSERT INTO contract_office_contexts(contract_id,created_by_staff_id,assigned_lawyer_id,client_mode,client_snapshot_json,billing_mode,original_price_egp,waiver_reason,notify_client) VALUES (?,?,?,?,?::jsonb,?,?,?,?)',[$id,$auth['id'],$assigned,$office['clientMode']??'office_internal',json_encode(['name'=>$office['clientName']??null,'email'=>$office['clientEmail']??null,'phone'=>$office['clientPhone']??null],JSON_UNESCAPED_UNICODE),$billing,$definition['priceEgp']??0,$waiver,$office['notifyClient']??false]);$this->audit->write($request,'contract.draft_created','contract',$id,null,['contractSerial'=>$serial,'templateSlug'=>$definition['slug']??null,'variantKey'=>$variantKey,'optionalKeys'=>$optional,'sourceChannel'=>$source]);return['id'=>$id,'serialNumber'=>$serial,'status'=>'draft','currentVersionId'=>(int)$ver->id];});
        return$this->created($request,$result,'تم حفظ مسودة العقد');
    }

    public function createShare(Request $request,int $id)
    {
        $auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$data=$request->validate(['permission'=>['nullable','in:view_only,edit'],'targetPublicId'=>['nullable','string','max:32'],'expiresInDays'=>['nullable','integer','min:1','max:30'],'editableFieldKeys'=>['nullable','array','max:100'],'editableFieldKeys.*'=>['string','max:140']]);$permission=($data['permission']??'view_only')==='edit'?'edit':'view_only';if(!config('zdraft.features.contract_editing'))$permission='view_only';if($permission==='edit'&&!in_array($c->status,['draft','revision_requested','client_review'],true))throw new ApiException(409,'يمكن مشاركة النسخة الحالية للعرض فقط');$window=$this->editWindow($c->edit_expires_at);if($permission==='edit'&&$c->status==='client_review'&&!$window['active'])throw new ApiException(409,'انتهت مهلة تعديل العقد ويمكن مشاركته للعرض فقط','EDIT_WINDOW_EXPIRED');$target=!empty($data['targetPublicId'])?strtoupper($data['targetPublicId']):null;if($target&&!DB::selectOne('SELECT 1 FROM users WHERE upper(public_id)=upper(?)',[$target]))throw new ApiException(400,'Z-ID المستهدف غير موجود');$editable=[];if($permission==='edit'){$core=array_fill_keys($this->engine->coreIdentityFieldKeys($this->json($c->template_definition),$c->variant_key),true);foreach(array_unique($data['editableFieldKeys']??[])as$key)if(!($c->core_identity_locked&&isset($core[$key])))$editable[]=$key;}$raw=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$expires=$data['expiresInDays']??7;$row=DB::selectOne("INSERT INTO contract_share_links(contract_id,created_by_user_id,token_hash,permission_level,target_public_id,editable_field_keys,expires_at) VALUES (?,?,?,?,?,?::jsonb,CURRENT_TIMESTAMP + (?::text || ' days')::interval) RETURNING id,expires_at",[$id,$auth['id'],hash('sha256',$raw),$permission,$target,json_encode($editable),$expires]);$this->audit->write($request,'contract.share_created','contract_share',(int)$row->id,null,['contractId'=>$id,'permission'=>$permission,'targetPublicId'=>$target,'editableFieldKeys'=>$editable,'expiresInDays'=>$expires]);return$this->created($request,['id'=>(int)$row->id,'token'=>$raw,'editableFieldKeys'=>$editable,'shareUrl'=>rtrim(config('zdraft.frontend_url'),'/').'/shared/'.$raw,'permission'=>$permission,'expiresAt'=>$row->expires_at],'تم إنشاء رابط مشاركة محدود الصلاحية');
    }
    public function revokeShare(Request $request,int $id,int $shareId){$auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$count=DB::table('contract_share_links')->where('id',$shareId)->where('contract_id',$id)->whereNull('revoked_at')->update(['revoked_at'=>now()]);if(!$count)throw new ApiException(404,'رابط المشاركة غير موجود أو ملغى');$this->audit->write($request,'contract.share_revoked','contract_share',$shareId,null,['contractId'=>$id]);return$this->ok($request,['revoked'=>true],'تم إلغاء رابط المشاركة');}
    public function my(Request $request){$uid=$this->auth($request)['id'];$rows=DB::select('SELECT c.id,c.serial_number AS "serialNumber",c.title,c.status,c.source_channel AS "sourceChannel",c.variant_key AS "variantKey",c.updated_at AS "updatedAt",ct.slug AS "templateSlug",ct.name_ar AS "templateNameAr" FROM contracts c JOIN contract_templates ct ON ct.id=c.template_id WHERE c.deleted_at IS NULL AND (c.user_id=? OR c.client_user_id=? OR c.created_by_user_id=? OR c.assigned_lawyer_id=?) ORDER BY c.updated_at DESC',[$uid,$uid,$uid,$uid]);return$this->ok($request,$rows);}

    public function pdf(Request $request,int $id):BinaryFileResponse
    {
        $auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);if($c->status!=='issued'||$c->pdf_status!=='ready'||!$c->pdf_path)throw new ApiException(409,'النسخة النهائية غير جاهزة للتنزيل بعد','PDF_NOT_READY');$doc=DB::selectOne("SELECT storage_path,storage_key FROM contract_document_files WHERE contract_id=? AND contract_version_id=? AND document_type='main' ORDER BY id DESC LIMIT 1",[$id,$c->current_version_id]);$path=$this->contractPath($doc->storage_key??null,$doc->storage_path??$c->pdf_path);if(!is_file($path))throw new ApiException(404,'ملف العقد غير موجود في التخزين','PDF_FILE_MISSING');return response()->download($path,preg_replace('/[^A-Za-z0-9._-]/','-',"{$c->serial_number}.pdf"),['Content-Type'=>'application/pdf']);
    }
    public function documents(Request $request,int $id){$auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$rows=DB::select('SELECT id,file_key AS "fileKey",document_type AS "documentType",optional_clause_key AS "optionalClauseKey",title_ar AS "titleAr",file_size_bytes AS "fileSizeBytes",sha256,created_at AS "createdAt" FROM contract_document_files WHERE contract_id=? AND contract_version_id=? ORDER BY CASE WHEN document_type=\'main\' THEN 0 ELSE 1 END,id',[$id,$c->current_version_id]);return$this->ok($request,$rows);}
    public function downloadDocument(Request $request,int $id,int $documentId):BinaryFileResponse{$auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$doc=DB::selectOne('SELECT storage_path,storage_key,title_ar FROM contract_document_files WHERE id=? AND contract_id=? AND contract_version_id=?',[$documentId,$id,$c->current_version_id]);if(!$doc)throw new ApiException(404,'المستند غير موجود');$path=$this->contractPath($doc->storage_key??null,$doc->storage_path);if(!is_file($path))throw new ApiException(404,'ملف المستند غير موجود في التخزين','DOCUMENT_FILE_MISSING');$name=preg_replace('/[^A-Za-z0-9._-]+/','-',"{$c->serial_number}-{$doc->title_ar}.pdf");return response()->download($path,$name,['Content-Type'=>'application/pdf']);}

    public function show(Request $request,int $id)
    {
        $auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$versions=DB::select('SELECT id,version_number AS "versionNumber",status,created_at AS "createdAt",locked_at AS "lockedAt",document_hash AS "documentHash",pdf_path AS "pdfPath" FROM contract_versions WHERE contract_id=? ORDER BY version_number DESC',[$id]);$definition=$this->json($c->template_definition);$optional=$this->jsonList($c->selected_optional_clause_keys);$window=$this->editWindow($c->edit_expires_at);$isOwner=in_array($auth['id'],[(int)$c->user_id,(int)($c->client_user_id??0)],true);$canDraft=in_array($c->status,['draft','revision_requested'],true);$canWindow=$isOwner&&$c->creation_mode==='self_service'&&$c->status==='client_review'&&$window['active'];$payload=$this->objectArray($c);$payload['template_definition']=$definition;$payload['field_values_json']=$this->json($c->field_values_json);$payload['selected_optional_clause_keys']=$optional;$payload['attachment_refs_json']=$this->json($c->attachment_refs_json);$payload['legal_clause_snapshot_json']=$this->jsonList($c->legal_clause_snapshot_json);$payload['versions']=$versions;$payload['coreIdentityFieldKeys']=$this->engine->coreIdentityFieldKeys($definition,$c->variant_key);$payload['fieldMetadata']=$this->fieldMetadata($definition,$c->variant_key,$optional);$payload['editWindow']=$window+['expiresAt'=>$c->edit_expires_at];$payload['permissions']=['canEdit'=>$canDraft||$canWindow,'canEditCoreIdentity'=>$canDraft&&!$c->core_identity_locked,'canRequestRevision'=>$isOwner&&in_array($c->status,['client_review','approved'],true),'canDownloadPdf'=>$c->status==='issued'&&$c->pdf_status==='ready'&&(bool)$c->pdf_path];return$this->ok($request,$payload);
    }

    public function updateDraft(Request $request,int $id)
    {
        $auth=$this->auth($request);$c=$this->contract($id);$this->assertAccess($auth,$c);$isOwner=in_array($auth['id'],[(int)$c->user_id,(int)($c->client_user_id??0)],true);$window=$this->editWindow($c->edit_expires_at);$ordinary=in_array($c->status,['draft','revision_requested'],true);$selfWindow=$isOwner&&$c->creation_mode==='self_service'&&$c->status==='client_review'&&$window['active'];if(!$ordinary&&!$selfWindow){if($c->creation_mode==='self_service'&&$c->status==='client_review'&&$window['expired'])throw new ApiException(409,'انتهت مهلة التعديل. اطلب خدمة تصحيح أو مراجعة من المكتب','EDIT_WINDOW_EXPIRED');throw new ApiException(409,'لا يمكن تعديل العقد في حالته الحالية');}
        $data=$request->validate(['fieldValues'=>['nullable','array'],'selectedOptionalClauseKeys'=>['nullable','array'],'variantKey'=>['nullable','string','max:140'],'attachmentRefs'=>['nullable','array'],'currentStepKey'=>['nullable','string','max:140']]);$currentFields=$this->json($c->field_values_json);$fields=$data['fieldValues']??$currentFields;$currentOptional=$this->jsonList($c->selected_optional_clause_keys);$optional=array_key_exists('selectedOptionalClauseKeys',$data)?array_map('strval',$data['selectedOptionalClauseKeys']):$currentOptional;$variant=$data['variantKey']??$c->variant_key;$attachments=$data['attachmentRefs']??$this->json($c->attachment_refs_json);$definition=$this->json($c->template_definition);
        if($selfWindow||$c->core_identity_locked){if($variant!==$c->variant_key)throw new ApiException(409,'لا يمكن تغيير نوع العقد بعد اعتماد الدفع','CONTRACT_VARIANT_LOCKED');if(json_encode($optional)!==json_encode($currentOptional))throw new ApiException(409,'لا يمكن تغيير الملاحق أو البنود المختارة بعد اعتماد الدفع','CONTRACT_OPTIONS_LOCKED');$core=array_fill_keys($this->engine->coreIdentityFieldKeys($definition,$c->variant_key),true);$changed=[];foreach(array_unique(array_merge(array_keys($currentFields),array_keys($fields)))as$key)if(json_encode($currentFields[$key]??null)!==json_encode($fields[$key]??null)&&isset($core[$key]))$changed[]=$key;if($changed)throw new ApiException(409,'بيانات الأطراف والعقار مقفلة بعد اعتماد الدفع','CORE_IDENTITY_LOCKED',$changed);}
        $validation=$this->engine->validateDraft($definition,$variant,$optional,$fields,$attachments);DB::transaction(function()use($request,$auth,$c,$id,$fields,$optional,$variant,$data,$attachments,$selfWindow){DB::statement('UPDATE contracts SET field_values_json=?::jsonb,selected_optional_clause_keys=?::jsonb,attachment_refs_json=?::jsonb,current_step_key=COALESCE(?,current_step_key),variant_key=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[json_encode($fields,JSON_UNESCAPED_UNICODE),json_encode($optional),json_encode($attachments,JSON_UNESCAPED_UNICODE),$data['currentStepKey']??null,$variant,$id]);DB::statement("UPDATE contract_versions SET field_values_json=?::jsonb,selected_optional_clause_keys=?::jsonb,variant_key=? WHERE id=? AND status IN ('draft','revision_requested','client_review','internal_review')",[json_encode($fields,JSON_UNESCAPED_UNICODE),json_encode($optional),$variant,$c->current_version_id]);if(isset($data['attachmentRefs']))$this->linkContractAttachments($attachments,$auth['id'],$id);$this->audit->write($request,$selfWindow?'contract.edit_window_updated':'contract.draft_updated','contract',$id,$this->json($c->field_values_json),$fields);});return$this->ok($request,['id'=>$id,'serialNumber'=>$c->serial_number,'status'=>$c->status,'currentVersionId'=>(int)$c->current_version_id,'editExpiresAt'=>$c->edit_expires_at,'issues'=>$validation['issues']],$validation['issues']?'تم الحفظ مع وجود بيانات مطلوبة':'تم حفظ التعديلات');
    }

    public function submit(Request $request,int $id)
    {
        $auth=$this->auth($request);$this->verified($auth);$c=$this->contract($id);$this->assertAccess($auth,$c);if(!in_array($c->status,['draft','revision_requested'],true))throw new ApiException(409,'العقد مرسل بالفعل أو لا يقبل الإرسال');$validation=$this->engine->validateDraft($this->json($c->template_definition),$c->variant_key,$this->jsonList($c->selected_optional_clause_keys),$this->json($c->field_values_json),$this->json($c->attachment_refs_json));if($validation['issues'])throw new ApiException(422,'أكمل البيانات المطلوبة قبل إرسال العقد','DRAFT_INCOMPLETE',$validation['issues']);$status=in_array($c->billing_mode,['office_waiver','external_collection'],true)?'pending_review':'pending_payment';DB::transaction(function()use($request,$c,$id,$status){DB::statement('UPDATE contracts SET status=?,submitted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?',[$status,$id]);DB::table('contract_versions')->where('id',$c->current_version_id)->update(['status'=>'internal_review']);$this->notifications->notifySuperAdmins('contract_submitted','عقد جديد يحتاج متابعة',"{$c->serial_number}: {$c->title}","/contracts/{$id}",['status'=>$status]);$this->audit->write($request,'contract.submitted','contract',$id,null,['status'=>$status]);});return$this->ok($request,['id'=>$id,'status'=>$status],$status==='pending_payment'?'تم إرسال العقد وهو بانتظار الدفع':'تم إرسال العقد للمراجعة');
    }
    public function revisionRequest(Request $request,int $id){$auth=$this->auth($request);$c=$this->contract($id);if(!in_array($auth['id'],[(int)$c->user_id,(int)($c->client_user_id??0)],true))throw new ApiException(403,'طلب التعديل متاح للعميل صاحب العقد فقط');if(!in_array($c->status,['client_review','approved'],true))throw new ApiException(409,'العقد ليس في مرحلة مراجعة العميل');$data=$request->validate(['notes'=>['required','string','max:5000']]);DB::transaction(function()use($request,$auth,$c,$id,$data){DB::statement("UPDATE contracts SET status='revision_requested',updated_at=CURRENT_TIMESTAMP WHERE id=?",[$id]);DB::table('contract_versions')->where('id',$c->current_version_id)->update(['status'=>'revision_requested']);DB::insert("INSERT INTO contract_review_cycles(contract_id,contract_version_id,reviewer_id,status,notes) VALUES (?,?,?,'changes_requested',?)",[$id,$c->current_version_id,$auth['id'],$data['notes']]);if($c->assigned_lawyer_id)$this->notifications->notify((int)$c->assigned_lawyer_id,'contract_revision_requested','تعديلات مطلوبة على العقد',"{$c->serial_number}: طلب العميل تعديلات","/contracts/{$id}",['notes'=>$data['notes']]);else$this->notifications->notifySuperAdmins('contract_revision_requested','تعديلات مطلوبة على العقد',"{$c->serial_number}: طلب العميل تعديلات","/contracts/{$id}",['notes'=>$data['notes']]);$this->audit->write($request,'contract.revision_requested','contract',$id,null,['notes'=>$data['notes']]);});return$this->ok($request,['id'=>$id,'status'=>'revision_requested'],'تم إرسال طلب التعديل');}
    public function finalize(Request $request,int $id){$auth=$this->auth($request);$this->verified($auth);$c=$this->contract($id);if(!in_array($auth['id'],[(int)$c->user_id,(int)($c->client_user_id??0)],true))throw new ApiException(403,'إصدار النسخة النهائية متاح لصاحب العقد فقط');$window=$this->editWindow($c->edit_expires_at);if($window['active']&&!$request->boolean('confirmEarlyFinalization'))throw new ApiException(409,'مهلة التعديل ما زالت متاحة. أكد رغبتك في الإصدار المبكر','EARLY_FINALIZATION_CONFIRMATION_REQUIRED',['expiresAt'=>$c->edit_expires_at]);$result=$this->lockAndQueue($request,$c,$auth['id'],true);return$this->ok($request,['id'=>$id,'status'=>'issued','pdfStatus'=>'queued','documentHash'=>$result['documentHash']],'تم إصدار العقد وإضافة ملف PDF إلى قائمة التجهيز');}

    public function adminIndex(Request $request){$auth=$this->auth($request);$status=$request->filled('status')?$request->string('status')->toString():null;$source=$request->filled('source')?$request->string('source')->toString():null;$search=$request->filled('search')?'%'.$request->string('search')->toString().'%':null;$viewAll=in_array('super_admin',$auth['roles']??[],true)||in_array('contracts.view_all',$auth['permissions']??[],true);$assigned=!$viewAll||$request->boolean('assignedToMe');$rows=DB::select('SELECT c.id,c.serial_number AS "serialNumber",c.title,c.status,c.source_channel AS "sourceChannel",c.billing_mode AS "billingMode",c.original_price_egp::float AS "originalPriceEgp",c.updated_at AS "updatedAt",ct.name_ar AS "templateNameAr",ct.slug AS "templateSlug",COALESCE(client.name,coc.client_snapshot_json->>\'name\',\'استخدام داخلي\') AS "clientName",lawyer.name AS "assignedLawyerName",creator.name AS "createdByName" FROM contracts c JOIN contract_templates ct ON ct.id=c.template_id LEFT JOIN users client ON client.id=COALESCE(c.client_user_id,c.user_id) LEFT JOIN users lawyer ON lawyer.id=c.assigned_lawyer_id LEFT JOIN users creator ON creator.id=c.created_by_user_id LEFT JOIN contract_office_contexts coc ON coc.contract_id=c.id WHERE c.deleted_at IS NULL AND (?::text IS NULL OR c.status=?) AND (?::text IS NULL OR c.source_channel=?) AND (?::text IS NULL OR c.serial_number ILIKE ? OR c.title ILIKE ? OR client.name ILIKE ?) AND (?::boolean=FALSE OR c.assigned_lawyer_id=?) ORDER BY c.updated_at DESC LIMIT 200',[$status,$status,$source,$source,$search,$search,$search,$search,$assigned,$auth['id']]);return$this->ok($request,$rows);}
    public function assign(Request $request,int $id){if(!config('zdraft.features.assignment'))throw new ApiException(404,'ميزة إسناد المحامين مخفية حاليًا','FEATURE_DISABLED');$data=$request->validate(['lawyerId'=>['required','integer','min:1']]);if(!DB::selectOne("SELECT u.id FROM users u JOIN staff_role_assignments sra ON sra.user_id=u.id JOIN roles r ON r.id=sra.role_id WHERE u.id=? AND r.role_key='lawyer' AND u.status='active'",[$data['lawyerId']]))throw new ApiException(400,'الحساب المختار ليس محاميًا نشطًا');DB::transaction(function()use($request,$id,$data){DB::statement("UPDATE contracts SET assigned_lawyer_id=?,status=CASE WHEN status='pending_review' THEN 'assigned' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$data['lawyerId'],$id]);$this->notifications->notify((int)$data['lawyerId'],'contract_assigned','تم إسناد عقد جديد إليك',"العقد رقم {$id} متاح في قائمة عملك","/contracts/{$id}");$this->audit->write($request,'contract.assigned','contract',$id,null,['lawyerId'=>$data['lawyerId']]);});return$this->ok($request,['id'=>$id,'lawyerId'=>(int)$data['lawyerId']],'تم إسناد العقد');}
    public function status(Request $request,int $id){$data=$request->validate(['status'=>['required','in:pending_review,assigned,in_progress,client_review,revision_requested,approved,cancelled'],'notes'=>['nullable','string','max:5000']]);$auth=$this->auth($request);$c=$this->contract($id);$this->assertStaff($auth,$c);DB::transaction(function()use($request,$c,$id,$data){DB::table('contracts')->where('id',$id)->update(['status'=>$data['status'],'updated_at'=>now()]);$this->notifications->notify((int)($c->client_user_id??$c->user_id),'contract_status_changed','تحديث حالة العقد',"{$c->serial_number}: الحالة الجديدة {$data['status']}","/contract/{$id}");$this->audit->write($request,'contract.status_changed','contract',$id,['status'=>$c->status],['status'=>$data['status'],'notes'=>$data['notes']??null]);});return$this->ok($request,['id'=>$id,'status'=>$data['status']],'تم تحديث حالة العقد');}
    public function paymentWaiver(Request $request,int $id){$data=$request->validate(['reason'=>['required','string','max:2000']]);$c=$this->contract($id);DB::transaction(function()use($request,$c,$id,$data){DB::statement("UPDATE contracts SET billing_mode='office_waiver',waiver_reason=?,status=CASE WHEN status='pending_payment' THEN 'pending_review' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$data['reason'],$id]);$this->audit->write($request,'contract.payment_waived','contract',$id,['billingMode'=>$c->billing_mode],['reason'=>$data['reason']]);});return$this->ok($request,['id'=>$id,'billingMode'=>'office_waiver'],'تم تسجيل الإعفاء وسببه');}

    public function createVersion(Request $request,int $id){if(!config('zdraft.features.contract_editing'))throw new ApiException(404,'تعديل العقود من لوحة التحكم مخفي حاليًا','FEATURE_DISABLED');$auth=$this->auth($request);$c=$this->contract($id);$this->assertStaff($auth,$c);$result=DB::transaction(function()use($request,$auth,$c,$id){DB::selectOne('SELECT id FROM contracts WHERE id=? FOR UPDATE',[$id]);$next=(int)DB::selectOne('SELECT COALESCE(MAX(version_number),0)+1 AS next FROM contract_versions WHERE contract_id=?',[$id])->next;$row=DB::selectOne("INSERT INTO contract_versions(contract_id,version_number,parent_version_id,template_version,template_version_id,variant_key,selected_optional_clause_keys,field_values_json,legal_clause_snapshot_json,status,created_by) VALUES (?,?,?,?,?,?,?::jsonb,?::jsonb,?::jsonb,'draft',?) RETURNING id",[$id,$next,$c->current_version_id,$c->template_version,$c->template_version_id,$c->variant_key,json_encode($this->jsonList($c->selected_optional_clause_keys)),json_encode($this->json($c->field_values_json),JSON_UNESCAPED_UNICODE),json_encode($this->jsonList($c->legal_clause_snapshot_json),JSON_UNESCAPED_UNICODE),$auth['id']]);DB::statement("UPDATE contracts SET current_version_id=?,status='in_progress',core_identity_locked=FALSE,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$row->id,$id]);$this->audit->write($request,'contract.version_created','contract',$id,null,['versionNumber'=>$next,'versionId'=>$row->id]);return['versionId'=>(int)$row->id,'versionNumber'=>$next];});return$this->created($request,$result,'تم إنشاء إصدار تعديل جديد مع الاحتفاظ بالإصدار السابق');}
    public function updateVersion(Request $request,int $id,int $versionId){if(!config('zdraft.features.contract_editing'))throw new ApiException(404,'تعديل العقود من لوحة التحكم مخفي حاليًا','FEATURE_DISABLED');$auth=$this->auth($request);$c=$this->contract($id);$this->assertStaff($auth,$c);if((int)$c->current_version_id!==$versionId)throw new ApiException(409,'يمكن تعديل الإصدار الحالي فقط');$v=DB::selectOne('SELECT status FROM contract_versions WHERE id=? AND contract_id=?',[$versionId,$id]);if(!$v)throw new ApiException(404,'إصدار العقد غير موجود');if(!in_array($v->status,['draft','internal_review','revision_requested'],true))throw new ApiException(409,'الإصدار مقفول أو غير قابل للتعديل');$data=$request->validate(['fieldValues'=>['nullable','array'],'selectedOptionalClauseKeys'=>['nullable','array'],'variantKey'=>['nullable','string','max:140'],'attachmentRefs'=>['nullable','array'],'currentStepKey'=>['nullable','string','max:140'],'notes'=>['nullable','string','max:5000']]);$fields=$data['fieldValues']??$this->json($c->field_values_json);$optional=$data['selectedOptionalClauseKeys']??$this->jsonList($c->selected_optional_clause_keys);$variant=$data['variantKey']??$c->variant_key;$attachments=$data['attachmentRefs']??$this->json($c->attachment_refs_json);$validation=$this->engine->validateDraft($this->json($c->template_definition),$variant,$optional,$fields,$attachments);DB::transaction(function()use($request,$auth,$c,$id,$versionId,$data,$fields,$optional,$variant,$attachments){DB::statement("UPDATE contract_versions SET field_values_json=?::jsonb,selected_optional_clause_keys=?::jsonb,variant_key=?,status='draft' WHERE id=? AND contract_id=?",[json_encode($fields,JSON_UNESCAPED_UNICODE),json_encode($optional),$variant,$versionId,$id]);DB::statement("UPDATE contracts SET field_values_json=?::jsonb,selected_optional_clause_keys=?::jsonb,variant_key=?,attachment_refs_json=?::jsonb,current_step_key=COALESCE(?,current_step_key),status='in_progress',updated_at=CURRENT_TIMESTAMP WHERE id=?",[json_encode($fields,JSON_UNESCAPED_UNICODE),json_encode($optional),$variant,json_encode($attachments,JSON_UNESCAPED_UNICODE),$data['currentStepKey']??null,$id]);if(isset($data['attachmentRefs']))$this->linkContractAttachments($attachments,$auth['id'],$id);$this->audit->write($request,'contract.version_updated','contract_version',$versionId,$this->json($c->field_values_json),['fieldValues'=>$fields,'optionalKeys'=>$optional,'variantKey'=>$variant,'notes'=>$data['notes']??null]);});return$this->ok($request,['contractId'=>$id,'versionId'=>$versionId,'issues'=>$validation['issues']],$validation['issues']?'تم حفظ الإصدار مع وجود بيانات مطلوبة':'تم حفظ إصدار العقد');}
    public function lock(Request $request,int $id){$auth=$this->auth($request);$c=$this->contract($id);$this->assertStaff($auth,$c);if(!in_array($c->status,['approved','client_review','in_progress'],true))throw new ApiException(409,'يجب استكمال المراجعة قبل قفل العقد');$result=$this->lockSnapshot($request,$c,$auth['id']);return$this->ok($request,['id'=>$id,'status'=>'locked','documentHash'=>$result['documentHash']],'تم قفل العقد وإنشاء لقطة قانونية ثابتة');}
    public function issue(Request $request,int $id){$auth=$this->auth($request);$c=$this->contract($id);$this->assertStaff($auth,$c);if($c->status!=='locked')throw new ApiException(409,'يجب قفل العقد قبل إصداره');DB::transaction(function()use($request,$auth,$c,$id){DB::statement("UPDATE contracts SET status='issued',pdf_status='queued',issued_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$id]);DB::table('contract_versions')->where('id',$c->current_version_id)->update(['status'=>'issued']);DB::insert("INSERT INTO document_jobs(contract_id,contract_version_id,job_type,status,payload_json) VALUES (?,?,'generate_pdf','pending',?::jsonb)",[$id,$c->current_version_id,json_encode(['requestedBy'=>$auth['id']])]);$this->notifications->notify((int)($c->client_user_id??$c->user_id),'contract_issued','تم إصدار عقدك',"{$c->serial_number}: يجري تجهيز ملف PDF النهائي","/contract/{$id}");$this->audit->write($request,'contract.issued','contract',$id,null,['queuedPdf'=>true]);});return$this->ok($request,['id'=>$id,'status'=>'issued','pdfJobQueued'=>true],'تم إصدار العقد وإضافة توليد PDF إلى قائمة المهام');}

    private function lockAndQueue(Request $request,object $c,int $actor,bool $force):array{$locked=$this->lockSnapshot($request,$c,$actor);DB::transaction(function()use($request,$c,$actor){DB::statement("UPDATE contracts SET status='issued',pdf_status='queued',issued_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$c->id]);DB::table('contract_versions')->where('id',$c->current_version_id)->update(['status'=>'issued']);DB::insert("INSERT INTO document_jobs(contract_id,contract_version_id,job_type,status,payload_json) VALUES (?,?,'generate_pdf','pending',?::jsonb)",[$c->id,$c->current_version_id,json_encode(['requestedBy'=>$actor])]);$this->notifications->notify($actor,'contract_issued','تم إصدار النسخة النهائية',"{$c->serial_number}: يجري تجهيز ملف PDF","/contract/{$c->id}");$this->audit->write($request,'contract.self_service_issued_early','contract',(int)$c->id,null,['documentHash'=>$this->currentHash((int)$c->current_version_id)]);});return$locked;}
    private function lockSnapshot(Request $request,object $c,int $actor):array{$definition=$this->json($c->template_definition);$fields=$this->json($c->field_values_json);$optional=$this->jsonList($c->selected_optional_clause_keys);$validation=$this->engine->validateDraft($definition,$c->variant_key,$optional,$fields,$this->json($c->attachment_refs_json));if($validation['issues'])throw new ApiException(422,'لا يمكن قفل عقد ببيانات ناقصة','DRAFT_INCOMPLETE',$validation['issues']);$rendered=$this->engine->renderLegalClauses($definition,$c->variant_key,$optional,$fields);if($rendered['missingClauseKeys'])throw new ApiException(422,'القالب لا يحتوي بعد على النصوص القانونية الكاملة لكل المواد المطلوبة','MISSING_LEGAL_CLAUSES',$rendered['missingClauseKeys']);if($rendered['missingVariables'])throw new ApiException(422,'توجد متغيرات قانونية بلا قيم','MISSING_LEGAL_VARIABLES',$rendered['missingVariables']);$snapshot=['templateVersionId'=>$c->template_version_id,'variantKey'=>$c->variant_key,'optionalKeys'=>$optional,'fieldValues'=>$fields,'clauses'=>$rendered['clauses']];$hash=hash('sha256',$this->stableJson($snapshot));DB::transaction(function()use($request,$c,$rendered,$hash){DB::statement("UPDATE contract_versions SET legal_clause_snapshot_json=?::jsonb,status='locked',document_hash=?,locked_at=CURRENT_TIMESTAMP WHERE id=?",[json_encode($rendered['clauses'],JSON_UNESCAPED_UNICODE),$hash,$c->current_version_id]);DB::statement("UPDATE contracts SET status='locked',core_identity_locked=TRUE,locked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",[$c->id]);$this->audit->write($request,'contract.locked','contract',(int)$c->id,null,['documentHash'=>$hash,'versionId'=>$c->current_version_id]);});return['documentHash'=>$hash];}

    private function auth(Request $r):array{return$r->attributes->get('auth_user')??throw new ApiException(401,'يجب تسجيل الدخول أولًا','UNAUTHENTICATED');}
    private function verified(array $a):void{if(!($a['emailVerified']??false))throw new ApiException(403,'يجب تأكيد البريد الإلكتروني أولًا','EMAIL_NOT_VERIFIED');}
    private function contract(int $id):object{$c=DB::selectOne('SELECT c.*,ct.slug AS template_slug,ct.name_ar AS template_name_ar,tv.definition_json AS template_definition,cv.version_number,cv.status AS version_status,cv.legal_clause_snapshot_json,u.name AS client_name,u.email AS client_email,lawyer.name AS assigned_lawyer_name,coc.client_snapshot_json,coc.billing_mode AS office_billing_mode,coc.waiver_reason AS office_waiver_reason,latest_payment.status AS payment_status,latest_payment.amount_egp AS payment_amount_egp,latest_payment.admin_notes AS payment_admin_notes,latest_payment.serial_number AS payment_serial_number FROM contracts c JOIN contract_templates ct ON ct.id=c.template_id JOIN template_versions tv ON tv.id=c.template_version_id LEFT JOIN contract_versions cv ON cv.id=c.current_version_id LEFT JOIN users u ON u.id=COALESCE(c.client_user_id,c.user_id) LEFT JOIN users lawyer ON lawyer.id=c.assigned_lawyer_id LEFT JOIN contract_office_contexts coc ON coc.contract_id=c.id LEFT JOIN LATERAL (SELECT p.status,p.amount_egp,p.admin_notes,p.serial_number FROM payments p WHERE p.contract_id=c.id ORDER BY p.created_at DESC,p.id DESC LIMIT 1) latest_payment ON TRUE WHERE c.id=? AND c.deleted_at IS NULL',[$id]);if(!$c)throw new ApiException(404,'العقد غير موجود');return$c;}
    private function assertAccess(array $a,object $c):void{if(in_array('super_admin',$a['roles']??[],true)||in_array('contracts.view_all',$a['permissions']??[],true)||in_array($a['id'],array_map('intval',array_filter([$c->user_id,$c->client_user_id,$c->created_by_user_id,$c->assigned_lawyer_id])),true))return;throw new ApiException(403,'ليس لديك صلاحية عرض هذا العقد');}
    private function assertStaff(array $a,object $c):void{if(in_array('super_admin',$a['roles']??[],true)||in_array('contracts.view_all',$a['permissions']??[],true)||(in_array('contracts.view_assigned',$a['permissions']??[],true)&&(int)$c->assigned_lawyer_id===$a['id']))return;throw new ApiException(403,'هذا العقد غير مسند إليك','CONTRACT_NOT_ASSIGNED');}
    private function publishedTemplate(string $slug):array{$r=DB::selectOne("SELECT ct.id AS template_id,tv.id AS version_id,tv.definition_json FROM contract_templates ct JOIN template_versions tv ON tv.id=ct.current_published_version_id WHERE ct.slug=? AND ct.is_active=TRUE AND tv.status='published'",[$slug]);if(!$r)throw new ApiException(404,'القالب المنشور غير موجود','TEMPLATE_NOT_PUBLISHED');return['templateId'=>(int)$r->template_id,'versionId'=>(int)$r->version_id,'definition'=>$this->json($r->definition_json)];}
    private function loadShare(string $token):object{$r=DB::selectOne('SELECT sl.*,c.serial_number,c.title,c.status,c.user_id,c.client_user_id,c.created_by_user_id,c.assigned_lawyer_id,c.field_values_json,c.attachment_refs_json,c.variant_key,c.selected_optional_clause_keys,c.template_version_id,c.core_identity_locked,c.edit_expires_at,tv.definition_json AS template_definition,ct.slug AS template_slug,owner.name AS owner_name FROM contract_share_links sl JOIN contracts c ON c.id=sl.contract_id JOIN contract_templates ct ON ct.id=c.template_id JOIN template_versions tv ON tv.id=c.template_version_id JOIN users owner ON owner.id=COALESCE(c.client_user_id,c.user_id) WHERE sl.token_hash=? AND sl.revoked_at IS NULL AND sl.expires_at>CURRENT_TIMESTAMP AND c.deleted_at IS NULL',[hash('sha256',$token)]);if(!$r)throw new ApiException(404,'رابط المشاركة غير صالح أو منتهي','SHARE_LINK_INVALID');return$r;}
    private function linkContractAttachments(array $refs,int $owner,int $contractId):void{$ids=[];foreach($refs as $values)if(is_array($values))foreach($values as$v)if(filter_var($v,FILTER_VALIDATE_INT)!==false)$ids[]=(int)$v;$ids=array_values(array_unique($ids));if(!$ids)return;$pg='{'.implode(',',$ids).'}';$rows=DB::select("SELECT id FROM document_attachments WHERE id=ANY(?::bigint[]) AND owner_user_id=? AND (attachable_type='pending' OR (attachable_type='contract' AND attachable_id=?)) FOR UPDATE",[$pg,$owner,$contractId]);if(count($rows)!==count($ids))throw new ApiException(400,'يوجد مرفق عقد غير صالح أو مرتبط بسجل آخر');DB::statement("UPDATE document_attachments SET attachable_type='contract',attachable_id=? WHERE id=ANY(?::bigint[]) AND attachable_type='pending'",[$contractId,$pg]);}
    private function editWindow(mixed $expires):array{if(!$expires)return['active'=>false,'expired'=>false,'remainingSeconds'=>0];$seconds=max(0,strtotime((string)$expires)-time());return['active'=>$seconds>0,'expired'=>$seconds<=0,'remainingSeconds'=>$seconds];}
    private function fieldMetadata(array $def,string $variant,array $optional):array{$resolved=$this->engine->resolve($def,$variant,$optional,[]);$out=[];foreach($resolved['steps']as$step)foreach($step['fields']??[]as$field)$out[$field['key']]=['labelAr'=>$field['labelAr']??$field['key'],'type'=>$field['type']??'text','options'=>$field['options']??[]];return$out;}
    private function contractPath(?string $key,string $legacy):string{if($key){try{return Storage::disk('contracts')->path($key);}catch(\Throwable){}}return$legacy;}
    private function serial(string $slug):string{return'SCP-'.now()->year.'-'.strtoupper(substr($slug,0,3)).'-'.strtoupper(substr(bin2hex(random_bytes(5)),0,8));}
    private function maskName(string $name):string{$parts=preg_split('/\s+/u',trim($name))?:[];return implode(' ',array_map(fn($p,$i)=>$i===0?$p:mb_substr($p,0,1).'***',$parts,array_keys($parts)));}
    private function json(mixed $v):array{if(is_array($v))return$v;if(is_object($v))return(array)$v;if(is_string($v))return json_decode($v,true)?:[];return[];}
    private function jsonList(mixed $v):array{return array_values($this->json($v));}
    private function objectArray(object $o):array{return get_object_vars($o);}
    private function stableJson(mixed $value):string{return json_encode($this->canonical($value),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION);}
    private function canonical(mixed $value):mixed{if(!is_array($value))return$value;if(array_is_list($value))return array_map(fn($v)=>$this->canonical($v),$value);ksort($value);foreach($value as$k=>$v)$value[$k]=$this->canonical($v);return$value;}
    private function currentHash(int $version):?string{return DB::selectOne('SELECT document_hash FROM contract_versions WHERE id=?',[$version])?->document_hash;}
}
