<?php
namespace App\Http\Controllers;
use App\Exceptions\ApiException;
use App\Services\AuditService;
use App\Services\NotificationService;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
final class PaymentController extends Controller
{
    use ApiResponse;
    public function __construct(private NotificationService $notifications,private AuditService $audit){}
    public function createReceipt(Request $request)
    {
        $auth=$request->attributes->get('auth_user');if(!$auth['emailVerified'])throw new ApiException(403,'يجب تأكيد البريد الإلكتروني أولًا','EMAIL_NOT_VERIFIED');
        $data=$request->validate(['contractId'=>['nullable','integer','min:1'],'serviceRequestId'=>['nullable','integer','min:1'],'amountEgp'=>['required','numeric','min:0'],'attachmentId'=>['required','integer','min:1'],'senderPhone'=>['nullable','string','max:30']]);
        $contractId=$data['contractId']??null;$serviceRequestId=$data['serviceRequestId']??null;if(!$contractId&&!$serviceRequestId)throw new ApiException(400,'حدد العقد أو طلب الخدمة المرتبط بالدفع');if($contractId&&$serviceRequestId)throw new ApiException(400,'اربط الإيصال بعقد واحد أو طلب خدمة واحد فقط');
        $serial='PAY-'.now()->year.'-'.strtoupper(substr(bin2hex(random_bytes(5)),0,8));$amount=(float)$data['amountEgp'];$uid=$auth['id'];
        $result=DB::transaction(function()use($request,$auth,$uid,$contractId,$serviceRequestId,$amount,$data,$serial){
            if($contractId){$c=DB::selectOne('SELECT id,status,original_price_egp FROM contracts WHERE id=? AND deleted_at IS NULL AND (user_id=? OR client_user_id=?) FOR UPDATE',[$contractId,$uid,$uid]);if(!$c)throw new ApiException(403,'العقد غير تابع لحسابك');if(!in_array($c->status,['draft','pending_payment'],true))throw new ApiException(409,'لا يمكن رفع دفع جديد للعقد في حالته الحالية','PAYMENT_NOT_ALLOWED');$expected=(float)$c->original_price_egp;if(abs($amount-$expected)>0.009)throw new ApiException(400,"المبلغ المطلوب لهذا العقد هو {$expected} ج.م",'PAYMENT_AMOUNT_MISMATCH');}
            if($serviceRequestId){$sr=DB::selectOne('SELECT id,request_type,status FROM service_requests WHERE id=? AND client_user_id=? FOR UPDATE',[$serviceRequestId,$uid]);if(!$sr)throw new ApiException(403,'طلب الخدمة غير تابع لحسابك');if($sr->status!=='awaiting_payment')throw new ApiException(409,'لا يمكن رفع دفع جديد لهذا الطلب في حالته الحالية','PAYMENT_NOT_ALLOWED');$key=$sr->request_type==='contract_review'?'services.contract_review.deposit_egp':($sr->request_type==='consultation'?'services.consultation.deposit_egp':'services.contract_drafting.deposit_egp');$setting=DB::selectOne("SELECT COALESCE((setting_value_json #>> '{}')::numeric,100)::text AS amount FROM platform_settings WHERE setting_key=?",[$key]);$expected=(float)($setting->amount??100);if(abs($amount-$expected)>0.009)throw new ApiException(400,"العربون المطلوب لهذه الخدمة هو {$expected} ج.م",'PAYMENT_AMOUNT_MISMATCH');}
            $duplicate=DB::selectOne("SELECT id,status FROM payments WHERE user_id=? AND contract_id IS NOT DISTINCT FROM ? AND service_request_id IS NOT DISTINCT FROM ? AND status IN ('pending_verification','approved') ORDER BY created_at DESC LIMIT 1",[$uid,$contractId,$serviceRequestId]);if($duplicate)throw new ApiException(409,'يوجد إثبات دفع قائم بالفعل لهذا الطلب','DUPLICATE_PAYMENT');
            $attachment=DB::selectOne("SELECT id FROM document_attachments WHERE id=? AND owner_user_id=? AND attachable_type='pending' FOR UPDATE",[$data['attachmentId'],$uid]);if(!$attachment)throw new ApiException(400,'إيصال الدفع غير موجود أو مرتبط بطلب آخر');
            $row=DB::selectOne("INSERT INTO payments (serial_number,user_id,contract_id,service_request_id,amount_egp,sender_phone,receipt_attachment_id,status,payment_method) VALUES (?,?,?,?,?,?,?,'pending_verification','vodafone_cash') RETURNING id",[$serial,$uid,$contractId,$serviceRequestId,$amount,$data['senderPhone']??null,$data['attachmentId']]);$id=(int)$row->id;
            DB::table('document_attachments')->where('id',$data['attachmentId'])->update(['attachable_type'=>'payment','attachable_id'=>$id]);if($contractId)DB::table('contracts')->where('id',$contractId)->where(fn($q)=>$q->where('user_id',$uid)->orWhere('client_user_id',$uid))->update(['status'=>'pending_payment','updated_at'=>now()]);
            $this->notifications->notify($uid,'payment_receipt_received','تم استلام إيصال الدفع',"{$serial}: الإيصال قيد المراجعة وسيصلك إشعار عند الاعتماد أو الرفض",$contractId?"/contract/{$contractId}":"/requests/{$serviceRequestId}");
            $this->notifications->notifySuperAdmins('payment_receipt_uploaded','إيصال دفع جديد يحتاج المراجعة',"{$serial} — {$amount} ج.م",'/payments',['paymentId'=>$id,'contractId'=>$contractId,'serviceRequestId'=>$serviceRequestId]);
            $this->audit->write($request,'payment.receipt_uploaded','payment',$id,null,compact('serial','amount','contractId','serviceRequestId'));
            return['id'=>$id,'serialNumber'=>$serial,'status'=>'pending_verification'];
        });
        return $this->created($request,$result,'تم استلام إيصال الدفع وهو قيد المراجعة');
    }
    public function my(Request $request){$rows=DB::select('SELECT id,serial_number AS "serialNumber",amount_egp::float AS "amountEgp",status,payment_method AS "paymentMethod",contract_id AS "contractId",service_request_id AS "serviceRequestId",admin_notes AS "adminNotes",created_at AS "createdAt" FROM payments WHERE user_id=? ORDER BY created_at DESC',[$request->attributes->get('auth_user')['id']]);return$this->ok($request,$rows);}
    public function adminIndex(Request $request){$status=$request->filled('status')?$request->string('status')->toString():null;$rows=DB::select('SELECT p.id,p.serial_number AS "serialNumber",p.amount_egp::float AS "amountEgp",p.status,p.sender_phone AS "senderPhone",p.receipt_attachment_id AS "receiptAttachmentId",p.contract_id AS "contractId",p.service_request_id AS "serviceRequestId",p.created_at AS "createdAt",u.name AS "clientName",u.email AS "clientEmail",u.phone AS "clientPhone",a.file_type AS "receiptMimeType",(a.thumbnail_storage_key IS NOT NULL OR a.thumbnail_file_path IS NOT NULL) AS "receiptThumbnailAvailable" FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN document_attachments a ON a.id=p.receipt_attachment_id WHERE (?::text IS NULL OR p.status=?) ORDER BY p.created_at DESC LIMIT 300',[$status,$status]);return$this->ok($request,$rows);}
    public function approve(Request $request,int $id)
    {
        $data=$request->validate(['notes'=>['nullable','string','max:2000']]);$admin=$request->attributes->get('auth_user')['id'];
        $result=DB::transaction(function()use($request,$id,$data,$admin){$row=DB::selectOne('SELECT * FROM payments WHERE id=? FOR UPDATE',[$id]);if(!$row)throw new ApiException(404,'عملية الدفع غير موجودة');if($row->status!=='pending_verification')throw new ApiException(409,'تمت مراجعة هذه العملية من قبل');DB::table('payments')->where('id',$id)->update(['status'=>'approved','admin_notes'=>$data['notes']??null,'reviewed_by_admin_id'=>$admin,'reviewed_at'=>now()]);$editHours=null;
            if($row->contract_id){$c=DB::selectOne('SELECT creation_mode,current_version_id FROM contracts WHERE id=? FOR UPDATE',[$row->contract_id]);if($c&&$c->creation_mode==='self_service'){$policy=DB::selectOne("SELECT LEAST(168,GREATEST(1,COALESCE((setting_value_json #>> '{}')::int,24))) AS edit_hours FROM platform_settings WHERE setting_key='contracts.self_service_edit_hours'");$editHours=(int)($policy->edit_hours??24);DB::statement("UPDATE contracts SET status='client_review',core_identity_locked=TRUE,edit_window_started_at=CURRENT_TIMESTAMP,edit_expires_at=CURRENT_TIMESTAMP + (?::text || ' hours')::interval,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending_payment'",[$editHours,$row->contract_id]);if($c->current_version_id)DB::table('contract_versions')->where('id',$c->current_version_id)->update(['status'=>'client_review']);}else DB::statement("UPDATE contracts SET status='pending_review',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending_payment'",[$row->contract_id]);}
            if($row->service_request_id)DB::table('service_requests')->where('id',$row->service_request_id)->update(['status'=>'new','updated_at'=>now()]);$message=$row->contract_id&&$editHours?"يمكنك مراجعة البيانات غير الأساسية لمدة {$editHours} ساعة قبل إصدار النسخة النهائية":$row->serial_number;$this->notifications->notify((int)$row->user_id,'payment_approved','تم اعتماد الدفع',$message,$row->contract_id?"/contract/{$row->contract_id}":"/requests/{$row->service_request_id}");$this->audit->write($request,'payment.approved','payment',$id,['status'=>$row->status],['status'=>'approved','notes'=>$data['notes']??null]);return['user_id'=>$row->user_id,'contract_id'=>$row->contract_id,'service_request_id'=>$row->service_request_id,'serial_number'=>$row->serial_number,'editHours'=>$editHours];});
        return$this->ok($request,['id'=>$id,'status'=>'approved']+$result,'تم اعتماد الدفع');
    }
    public function reject(Request $request,int $id)
    {
        $data=$request->validate(['reason'=>['required','string','max:2000']]);$admin=$request->attributes->get('auth_user')['id'];$result=DB::transaction(function()use($request,$id,$data,$admin){$row=DB::selectOne('SELECT * FROM payments WHERE id=? FOR UPDATE',[$id]);if(!$row)throw new ApiException(404,'عملية الدفع غير موجودة');if($row->status!=='pending_verification')throw new ApiException(409,'تمت مراجعة هذه العملية من قبل');DB::table('payments')->where('id',$id)->update(['status'=>'rejected','admin_notes'=>$data['reason'],'reviewed_by_admin_id'=>$admin,'reviewed_at'=>now()]);$this->notifications->notify((int)$row->user_id,'payment_rejected','تعذر اعتماد الدفع',$data['reason'],$row->contract_id?"/contract/{$row->contract_id}":"/requests/{$row->service_request_id}");$this->audit->write($request,'payment.rejected','payment',$id,['status'=>$row->status],['status'=>'rejected','reason'=>$data['reason']]);return['user_id'=>$row->user_id,'contract_id'=>$row->contract_id,'service_request_id'=>$row->service_request_id,'serial_number'=>$row->serial_number];});return$this->ok($request,['id'=>$id,'status'=>'rejected']+$result,'تم رفض الإيصال وإشعار العميل');
    }
}
