"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apartmentSaleTemplateDefinition = void 0;
const sourceClauses_1 = require("../../legal-content/sourceClauses");
const partyTypeOptions = [
    { value: "individual", labelAr: "فرد" },
    { value: "company", labelAr: "شركة / منشأة" },
];
const salePartyFields = (prefix, partyLabel) => [
    { key: `${prefix}_party_type`, type: "radio", labelAr: `صفة ${partyLabel}`, required: true, options: partyTypeOptions },
    { key: `${prefix}_name`, type: "text", labelAr: `الاسم الكامل لـ${partyLabel}`, required: true },
    { key: `${prefix}_nationality`, type: "text", labelAr: "الجنسية", required: true },
    { key: `${prefix}_national_id`, type: "text", labelAr: "الرقم القومي / جواز السفر", required: true },
    { key: `${prefix}_id_issuer`, type: "text", labelAr: "جهة الإصدار" },
    { key: `${prefix}_id_issue_date`, type: "date", labelAr: "تاريخ الإصدار" },
    { key: `${prefix}_address`, type: "text", labelAr: "العنوان", required: true },
    { key: `${prefix}_phone`, type: "text", labelAr: "رقم الهاتف", required: true },
    { key: `${prefix}_email`, type: "text", labelAr: "البريد الإلكتروني" },
    { key: `${prefix}_company_name`, type: "text", labelAr: "اسم الشركة", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_company_legal_form`, type: "text", labelAr: "الشكل القانوني", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_commercial_register`, type: "text", labelAr: "السجل التجاري", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_tax_card`, type: "text", labelAr: "البطاقة الضريبية", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_legal_representative`, type: "text", labelAr: "الممثل القانوني", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_representative_capacity`, type: "text", labelAr: "صفة الممثل", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_company_address`, type: "text", labelAr: "مقر الشركة", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `${prefix}_company_email`, type: "text", labelAr: "البريد الإلكتروني للشركة", required: true, visibleWhen: { fieldKey: `${prefix}_party_type`, operator: "equals", value: "company" } },
    { key: `sale_${prefix}_id_front`, type: "attachment", labelAr: `وجه بطاقة ${partyLabel}`, required: true },
    { key: `sale_${prefix}_id_back`, type: "attachment", labelAr: `ظهر بطاقة ${partyLabel}`, required: true },
];
const saleCommonSteps = [
    { key: "sale_seller", titleAr: "بيانات البائع", articleRange: "هوية وصفة الطرف", fields: salePartyFields("seller", "البائع") },
    { key: "sale_buyer", titleAr: "بيانات المشتري", articleRange: "هوية وصفة الطرف", fields: salePartyFields("buyer", "المشتري") },
    { key: "sale_unit", titleAr: "الوحدة السكنية", articleRange: "الموقع والمواصفات", fields: [
            { key: "sale_unit_governorate", type: "text", labelAr: "المحافظة", required: true },
            { key: "sale_unit_city", type: "text", labelAr: "المدينة / المركز", required: true },
            { key: "sale_unit_district", type: "text", labelAr: "الحي / المنطقة", required: true },
            { key: "sale_unit_street", type: "text", labelAr: "اسم الشارع", required: true },
            { key: "sale_compound_name", type: "text", labelAr: "اسم الكمبوند" },
            { key: "sale_plot_number", type: "text", labelAr: "رقم القطعة" },
            { key: "sale_adjacency_number", type: "text", labelAr: "رقم المجاورة" },
            { key: "sale_building_number", type: "text", labelAr: "رقم العقار" },
            { key: "sale_building_name", type: "text", labelAr: "اسم البرج / العمارة" },
            { key: "sale_floor_number", type: "text", labelAr: "الدور", required: true },
            { key: "sale_unit_number", type: "text", labelAr: "رقم الوحدة", required: true },
            { key: "sale_unit_area", type: "number", labelAr: "المساحة الإجمالية بالمتر", required: true, validation: { min: 1 } },
            { key: "sale_bedrooms_count", type: "number", labelAr: "عدد غرف النوم", required: true, validation: { min: 0 } },
            { key: "sale_reception_count", type: "number", labelAr: "عدد صالات الاستقبال", required: true, validation: { min: 0 } },
            { key: "sale_bathrooms_count", type: "number", labelAr: "عدد الحمامات", required: true, validation: { min: 0 } },
            { key: "sale_balconies_count", type: "number", labelAr: "عدد البلكونات", required: true, validation: { min: 0 } },
            { key: "sale_has_kitchen", type: "radio", labelAr: "هل يوجد مطبخ؟", required: true, options: [{ value: "yes", labelAr: "نعم" }, { value: "no", labelAr: "لا" }] },
            { key: "sale_finishing_level", type: "select", labelAr: "وصف التشطيب", required: true, options: [
                    { value: "unfinished", labelAr: "بدون تشطيب" }, { value: "semi_finished", labelAr: "نصف تشطيب" },
                    { value: "finished", labelAr: "تشطيب كامل" }, { value: "lux", labelAr: "لوكس" },
                    { value: "super_lux", labelAr: "سوبر لوكس" }, { value: "super_high_lux", labelAr: "سوبر هاي لوكس" },
                ] },
        ] },
    { key: "sale_meters_boundaries", titleAr: "العدادات والحدود", articleRange: "مرافق وحدود", fields: [
            { key: "sale_electricity_meter", type: "text", labelAr: "رقم عداد الكهرباء" },
            { key: "sale_electricity_meter_type", type: "select", labelAr: "نوع عداد الكهرباء", options: [{ value: "independent", labelAr: "مستقل" }, { value: "shared", labelAr: "مشترك" }] },
            { key: "sale_water_meter", type: "text", labelAr: "رقم عداد المياه" },
            { key: "sale_water_meter_type", type: "select", labelAr: "نوع عداد المياه", options: [{ value: "independent", labelAr: "مستقل" }, { value: "shared", labelAr: "مشترك" }] },
            { key: "sale_gas_meter", type: "text", labelAr: "رقم عداد الغاز" },
            { key: "sale_gas_meter_type", type: "select", labelAr: "نوع عداد الغاز", options: [{ value: "independent", labelAr: "مستقل" }, { value: "shared", labelAr: "مشترك" }, { value: "none", labelAr: "غير موجود" }] },
            { key: "sale_north_boundary", type: "text", labelAr: "الحد البحري", required: true },
            { key: "sale_south_boundary", type: "text", labelAr: "الحد القبلي", required: true },
            { key: "sale_east_boundary", type: "text", labelAr: "الحد الشرقي", required: true },
            { key: "sale_west_boundary", type: "text", labelAr: "الحد الغربي", required: true },
        ] },
    { key: "sale_ownership", titleAr: "سند الملكية", articleRange: "مصدر وتسلسل الملكية", fields: [
            { key: "ownership_source_type", type: "select", labelAr: "نوع سند الملكية", required: true, options: [
                    { value: "preliminary_contract", labelAr: "عقد بيع ابتدائي" }, { value: "custom_contract", labelAr: "عقد عرفي" },
                    { value: "registered_contract", labelAr: "عقد مسجل" }, { value: "court_judgment", labelAr: "حكم قضائي" },
                    { value: "inheritance", labelAr: "إعلام وراثة" }, { value: "allocation", labelAr: "تخصيص من جهة" }, { value: "other", labelAr: "أخرى" },
                ] },
            { key: "ownership_source_other", type: "text", labelAr: "بيان السند الآخر", visibleWhen: { fieldKey: "ownership_source_type", operator: "equals", value: "other" } },
            { key: "sale_ownership_documents", type: "attachment", labelAr: "مستندات سند الملكية", required: true },
        ] },
    { key: "sale_price", titleAr: "ثمن البيع", articleRange: "القيمة الإجمالية", fields: [
            { key: "sale_total_price", type: "money", labelAr: "إجمالي ثمن البيع", required: true, validation: { min: 1 } },
        ] },
    { key: "sale_payment", titleAr: "طريقة السداد", articleRange: "مخالصة أو سداد مؤجل", fields: [
            { key: "sale_payment_method", type: "select", labelAr: "حالة وطريقة سداد الثمن", required: true, options: [
                    { value: "cash_full", labelAr: "سداد كامل نقدًا" }, { value: "bank_full", labelAr: "سداد كامل بتحويل" },
                    { value: "partial", labelAr: "مقدم وباقٍ" }, { value: "installments", labelAr: "جدول أقساط بملحق مستقل" },
                ] },
            { key: "sale_down_payment", type: "money", labelAr: "المقدم المسدد", required: true, visibleWhen: { fieldKey: "sale_payment_method", operator: "includes", value: "partial" }, validation: { min: 0 } },
            { key: "sale_remaining_amount", type: "money", labelAr: "المبلغ المتبقي", required: true, visibleWhen: { fieldKey: "sale_payment_method", operator: "includes", value: "partial" }, validation: { min: 0 } },
            { key: "sale_payment_notes", type: "textarea", labelAr: "بيانات أو إثبات السداد" },
        ] },
    { key: "sale_handover", titleAr: "التسليم", articleRange: "حيازة ومفاتيح", fields: [
            { key: "sale_handover_immediate", type: "radio", labelAr: "هل تم التسليم عند التوقيع؟", required: true, options: [{ value: "yes", labelAr: "نعم" }, { value: "no", labelAr: "لا" }] },
            { key: "sale_handover_date", type: "date", labelAr: "تاريخ التسليم", required: true, visibleWhen: { fieldKey: "sale_handover_immediate", operator: "equals", value: "no" } },
            { key: "sale_handover_keys_count", type: "number", labelAr: "عدد المفاتيح المسلمة", validation: { min: 0 } },
            { key: "sale_occupancy_status", type: "select", labelAr: "حالة إشغال الوحدة", required: true, options: [
                    { value: "vacant", labelAr: "خالية" }, { value: "seller_occupied", labelAr: "مشغولة بالبائع" },
                    { value: "tenant_occupied", labelAr: "مؤجرة" }, { value: "third_party", labelAr: "بها واضع يد / طرف ثالث" },
                ] },
            { key: "sale_occupancy_details", type: "textarea", labelAr: "تفاصيل الإشغال أو الإخلاء", required: true, visibleWhen: { fieldKey: "sale_occupancy_status", operator: "not_equals", value: "vacant" } },
        ] },
    { key: "sale_utilities", titleAr: "المرافق", articleRange: "مستحقات ونقل عدادات", fields: [
            { key: "seller_paid_electricity", type: "checkbox", labelAr: "الكهرباء مسددة حتى التسليم" },
            { key: "seller_paid_water", type: "checkbox", labelAr: "المياه مسددة حتى التسليم" },
            { key: "seller_paid_gas", type: "checkbox", labelAr: "الغاز مسدد حتى التسليم" },
            { key: "seller_paid_maintenance", type: "checkbox", labelAr: "الصيانة / اتحاد الملاك مسدد" },
            { key: "meter_transfer_fees_payer", type: "select", labelAr: "من يتحمل نقل العدادات؟", options: [{ value: "buyer", labelAr: "المشتري" }, { value: "seller", labelAr: "البائع" }, { value: "shared", labelAr: "مناصفة" }] },
        ] },
    { key: "sale_guarantees", titleAr: "الضمانات", articleRange: "رهن ونزاع وحجز", fields: [
            { key: "sale_has_mortgage", type: "checkbox", labelAr: "يوجد رهن" },
            { key: "sale_has_dispute", type: "checkbox", labelAr: "يوجد نزاع" },
            { key: "sale_has_attachment", type: "checkbox", labelAr: "يوجد حجز" },
            { key: "sale_has_usufruct", type: "checkbox", labelAr: "يوجد حق انتفاع أو ارتفاق مؤثر" },
            { key: "sale_encumbrance_notes", type: "textarea", labelAr: "شرح القيود أو النزاعات إن وجدت" },
            { key: "sale_inspection_acknowledged", type: "checkbox", labelAr: "يقر المشتري بإتمام المعاينة وقبول الحالة الظاهرة", required: true },
        ] },
    { key: "sale_broker_registration", titleAr: "الوسيط والتسجيل", articleRange: "رسوم وإجراءات", fields: [
            { key: "has_broker", type: "radio", labelAr: "هل يوجد وسيط؟", options: [{ value: "yes", labelAr: "نعم" }, { value: "no", labelAr: "لا" }] },
            { key: "broker_name", type: "text", labelAr: "اسم الوسيط", required: true, visibleWhen: { fieldKey: "has_broker", operator: "equals", value: "yes" } },
            { key: "broker_phone", type: "text", labelAr: "هاتف الوسيط", required: true, visibleWhen: { fieldKey: "has_broker", operator: "equals", value: "yes" } },
            { key: "broker_commission", type: "money", labelAr: "قيمة العمولة", required: true, visibleWhen: { fieldKey: "has_broker", operator: "equals", value: "yes" } },
            { key: "broker_commission_payer", type: "select", labelAr: "من يتحمل العمولة؟", required: true, visibleWhen: { fieldKey: "has_broker", operator: "equals", value: "yes" }, options: [{ value: "buyer", labelAr: "المشتري" }, { value: "seller", labelAr: "البائع" }, { value: "shared", labelAr: "مناصفة" }] },
            { key: "is_unit_registered", type: "select", labelAr: "حالة التسجيل بالشهر العقاري", options: [{ value: "yes", labelAr: "مسجلة" }, { value: "no", labelAr: "غير مسجلة" }, { value: "unknown", labelAr: "غير معلوم" }] },
            { key: "registration_number", type: "text", labelAr: "رقم التسجيل", required: true, visibleWhen: { fieldKey: "is_unit_registered", operator: "equals", value: "yes" } },
            { key: "registration_date", type: "date", labelAr: "تاريخ التسجيل", required: true, visibleWhen: { fieldKey: "is_unit_registered", operator: "equals", value: "yes" } },
            { key: "real_estate_disposition_tax_payer", type: "select", labelAr: "ضريبة التصرفات العقارية", options: [{ value: "seller", labelAr: "على البائع وفق القانون" }, { value: "other_agreement", labelAr: "وفق اتفاق خاص مع مراعاة القانون" }] },
            { key: "registration_fees_payer", type: "select", labelAr: "رسوم التسجيل", options: [{ value: "buyer", labelAr: "المشتري" }, { value: "seller", labelAr: "البائع" }, { value: "shared", labelAr: "مناصفة" }] },
        ] },
    { key: "sale_attachments_court", titleAr: "المرفقات والمحكمة", articleRange: "ملفات واختصاص", fields: [
            { key: "sale_utility_receipts", type: "attachment", labelAr: "آخر إيصالات المرافق" },
            { key: "sale_extra_docs", type: "attachment", labelAr: "مستندات أخرى" },
            { key: "sale_competent_court", type: "text", labelAr: "المحكمة المختصة", required: true },
        ] },
];
const saleReviewStep = {
    key: "sale_review",
    titleAr: "المراجعة والاعتماد",
    articleRange: "ملخص نهائي",
    fields: [],
};
const sharedSaleDefaults = {
    seller_party_type: "individual",
    buyer_party_type: "individual",
    seller_nationality: "مصر",
    buyer_nationality: "مصر",
    sale_bedrooms_count: "2",
    sale_reception_count: "1",
    sale_bathrooms_count: "1",
    sale_balconies_count: "1",
    sale_has_kitchen: "yes",
    sale_finishing_level: "lux",
    sale_payment_method: "cash_full",
    sale_handover_immediate: "yes",
    seller_paid_electricity: true,
    seller_paid_water: true,
    seller_paid_gas: true,
    seller_paid_maintenance: true,
    meter_transfer_fees_payer: "buyer",
    sale_has_mortgage: false,
    sale_has_dispute: false,
    sale_has_attachment: false,
    sale_has_usufruct: false,
    has_broker: "no",
    broker_commission_payer: "buyer",
    sale_electricity_meter_type: "independent",
    sale_water_meter_type: "independent",
    sale_gas_meter_type: "independent",
    sale_occupancy_status: "vacant",
    real_estate_disposition_tax_payer: "seller",
    registration_fees_payer: "buyer",
    sale_inspection_acknowledged: false,
    sale_competent_court: "القاهرة",
};
const preliminaryVariantStep = {
    key: "sale_preliminary_details",
    titleAr: "تفاصيل البيع الابتدائي",
    articleRange: "التسلسل والتصالح والملحقات",
    sourceClauseKey: "sale_preliminary_variant",
    fields: [
        {
            key: "preliminary_ownership_chain",
            type: "repeater",
            labelAr: "تسلسل العقود أو التصرفات السابقة",
            helpText: "أضف كل سند سابق يوضح كيف انتقلت الوحدة حتى وصلت إلى البائع الحالي.",
            minRows: 1,
            required: true,
            columns: [
                { key: "document_type", type: "text", labelAr: "نوع السند", required: true, placeholder: "عقد بيع ابتدائي / عرفي / حكم" },
                { key: "document_date", type: "date", labelAr: "تاريخ السند", required: true },
                { key: "from_party", type: "text", labelAr: "صادر من", required: true },
                { key: "to_party", type: "text", labelAr: "إلى", required: true },
                { key: "notes", type: "text", labelAr: "ملاحظات" },
            ],
        },
        {
            key: "sale_includes_common_areas",
            type: "radio",
            labelAr: "هل يشمل البيع الحصة الشائعة والأجزاء والمرافق المشتركة؟",
            required: true,
            options: [
                { value: "yes", labelAr: "نعم" },
                { value: "no", labelAr: "لا - حسب حدود وسند البيع" },
            ],
        },
        {
            key: "sale_garage_status",
            type: "radio",
            labelAr: "موقف الجراج أو مكان السيارة",
            required: true,
            options: [
                { value: "included", labelAr: "مشمول في البيع" },
                { value: "allocated_use", labelAr: "حق انتفاع/تخصيص استعمال" },
                { value: "not_included", labelAr: "غير مشمول" },
            ],
        },
        {
            key: "sale_garage_description",
            type: "text",
            labelAr: "وصف مكان السيارة أو سند تخصيصه",
            visibleWhen: { fieldKey: "sale_garage_status", operator: "not_equals", value: "not_included" },
        },
        {
            key: "reconciliation_status",
            type: "radio",
            labelAr: "موقف التصالح على مخالفات البناء",
            required: true,
            options: [
                { value: "none", labelAr: "لا توجد مخالفة معلنة" },
                { value: "submitted", labelAr: "يوجد طلب تصالح مقدم" },
                { value: "approved", labelAr: "صدر قرار/نموذج قبول" },
                { value: "unknown", labelAr: "غير معلوم ويحتاج مراجعة" },
            ],
        },
        {
            key: "reconciliation_request_number",
            type: "text",
            labelAr: "رقم طلب التصالح",
            visibleWhen: { fieldKey: "reconciliation_status", operator: "not_equals", value: "none" },
        },
        {
            key: "reconciliation_responsible_party",
            type: "select",
            labelAr: "من يستكمل إجراءات التصالح؟",
            visibleWhen: { fieldKey: "reconciliation_status", operator: "equals", value: "submitted" },
            options: [
                { value: "seller", labelAr: "البائع" },
                { value: "buyer", labelAr: "المشتري بعد التنازل عن الطلب" },
            ],
        },
    ],
};
const registrableVariantStep = {
    key: "sale_registration_details",
    titleAr: "بيانات الشهر العقاري والتسجيل",
    articleRange: "السند المشهر وإجراءات النقل",
    sourceClauseKey: "sale_registrable_variant",
    fields: [
        {
            key: "registered_title_type",
            type: "select",
            labelAr: "السند الذي يثبت ملكية البائع",
            required: true,
            options: [
                { value: "registered_contract", labelAr: "عقد بيع مسجل" },
                { value: "final_judgment", labelAr: "حكم نهائي مثبت للملكية" },
                { value: "allocation_registered", labelAr: "تخصيص/محرر قابل للشهر" },
                { value: "other", labelAr: "سند آخر صالح للتسجيل" },
            ],
        },
        { key: "registered_deed_number", type: "text", labelAr: "رقم السند أو رقم الشهر", required: true },
        { key: "registered_deed_year", type: "number", labelAr: "السنة", required: true, validation: { min: 1900, max: 2200 } },
        { key: "registry_office", type: "text", labelAr: "مكتب/مأمورية الشهر العقاري", required: true },
        { key: "registration_application_number", type: "text", labelAr: "رقم طلب الشهر أو المأمورية إن وجد" },
        {
            key: "registration_completion_method",
            type: "radio",
            labelAr: "طريقة استكمال نقل الملكية",
            required: true,
            options: [
                { value: "direct_registration", labelAr: "التسجيل المباشر" },
                { value: "validity_enforcement_case", labelAr: "دعوى صحة ونفاذ عند الحاجة" },
            ],
        },
        { key: "registration_deadline_days", type: "number", labelAr: "المدة المستهدفة لبدء الإجراءات (يوم)", validation: { min: 1, max: 3650 } },
        { key: "registration_notes", type: "textarea", labelAr: "ملاحظات واقعية على ملف التسجيل", placeholder: "بيانات ناقصة أو مستند مطلوب - دون كتابة صياغة قانونية حرة." },
    ],
};
const inheritedVariantStep = {
    key: "sale_inheritance_details",
    titleAr: "بيانات الميراث وحق التصرف",
    articleRange: "إعلام الوراثة وموافقات الورثة",
    sourceClauseKey: "sale_inherited_variant",
    fields: [
        { key: "deceased_owner_name", type: "text", labelAr: "اسم المورث", required: true },
        { key: "inheritance_declaration_number", type: "text", labelAr: "رقم إعلام الوراثة", required: true },
        { key: "inheritance_declaration_court", type: "text", labelAr: "المحكمة الصادر منها إعلام الوراثة", required: true },
        { key: "inheritance_declaration_date", type: "date", labelAr: "تاريخ إعلام الوراثة", required: true },
        { key: "seller_inherited_share", type: "text", labelAr: "حصة البائع الموروثة في الوحدة", required: true, placeholder: "مثال: كامل الوحدة / نصف مشاع / 6 قراريط" },
        {
            key: "inheritance_disposition_basis",
            type: "select",
            labelAr: "سند انفراد البائع بحق التصرف",
            required: true,
            options: [
                { value: "sole_heir", labelAr: "البائع هو الوارث الوحيد" },
                { value: "power_of_attorney", labelAr: "توكيل من باقي الورثة" },
                { value: "partition_contract", labelAr: "عقد قسمة بين الورثة" },
                { value: "relinquishment_contract", labelAr: "عقد تخارج أو تنازل" },
                { value: "sale_from_heirs", labelAr: "عقد بيع/تصرف صادر من باقي الورثة" },
                { value: "all_heirs_signing", labelAr: "جميع الورثة أطراف/موقعون" },
            ],
        },
        {
            key: "inheritance_basis_document_details",
            type: "text",
            labelAr: "رقم وتاريخ سند التصرف من باقي الورثة",
            visibleWhen: { fieldKey: "inheritance_disposition_basis", operator: "not_equals", value: "sole_heir" },
        },
        {
            key: "other_heirs",
            type: "repeater",
            labelAr: "بيانات باقي الورثة أو أصحاب الحقوق",
            columns: [
                { key: "name", type: "text", labelAr: "الاسم", required: true },
                { key: "national_id", type: "text", labelAr: "الرقم القومي" },
                { key: "relationship", type: "text", labelAr: "صلة القرابة" },
                { key: "share", type: "text", labelAr: "الحصة" },
                { key: "approval_basis", type: "text", labelAr: "سند الموافقة/التنازل" },
            ],
        },
        { key: "minor_or_incapacitated_heirs", type: "checkbox", labelAr: "يوجد قاصر أو ناقص/عديم أهلية ضمن الورثة" },
        {
            key: "family_court_authorization",
            type: "textarea",
            labelAr: "بيانات إذن محكمة الأسرة أو الإجراء الخاص",
            required: true,
            visibleWhen: { fieldKey: "minor_or_incapacitated_heirs", operator: "truthy" },
        },
    ],
};
function createSaleVariant(input) {
    return {
        key: input.key,
        nameAr: input.nameAr,
        documentTitleAr: input.documentTitleAr,
        description: input.description,
        sourceDocumentName: input.sourceDocumentName,
        steps: [
            ...saleCommonSteps.flatMap((step) => step.key === "sale_ownership" ? [step, input.step] : [step]),
            saleReviewStep,
        ],
        requiredClauseKeys: [...input.requiredClauseKeys],
        allowedOptionalClauseKeys: ["sale_installment_schedule"],
        defaultFieldValues: { ...sharedSaleDefaults, ...input.defaults },
    };
}
exports.apartmentSaleTemplateDefinition = {
    slug: "apartment_sale",
    version: 4,
    nameAr: "عقود بيع الوحدات السكنية",
    description: "قالب بيع رئيسي بثلاث صيغ قانونية مستقلة، مع إمكانية إصدار ملحق أقساط منفصل.",
    priceEgp: 149,
    variants: [
        createSaleVariant({
            key: "preliminary_sale",
            nameAr: "عقد بيع ابتدائي",
            documentTitleAr: "عقد بيع ابتدائي لوحدة سكنية",
            description: "للبيع المستند إلى عقود أو تصرفات عرفية/ابتدائية، مع تسلسل ملكية وموقف التصالح والحصة الشائعة.",
            sourceDocumentName: "عقد بيع ابتدائي Z DRAFT.pdf",
            step: preliminaryVariantStep,
            requiredClauseKeys: [...sourceClauses_1.saleSourceClauseKeysByVariant.preliminary_sale],
            defaults: {
                ownership_source_type: "initial_sale_contract",
                is_unit_registered: "no",
                sale_includes_common_areas: "yes",
                sale_garage_status: "not_included",
                reconciliation_status: "none",
            },
        }),
        createSaleVariant({
            key: "registrable_sale",
            nameAr: "عقد بيع قابل للتسجيل بالشهر العقاري",
            documentTitleAr: "عقد بيع وحدة سكنية قابل للتسجيل بالشهر العقاري",
            description: "للبيع الذي يستند إلى سند صالح للشهر، مع بيانات السند ومأمورية التسجيل والتزامات نقل الملكية.",
            sourceDocumentName: "عقد بيع قابل للتسجيل في الشهر العقاري Z DRAFT.pdf",
            step: registrableVariantStep,
            requiredClauseKeys: [...sourceClauses_1.saleSourceClauseKeysByVariant.registrable_sale],
            defaults: {
                ownership_source_type: "registered_sale_contract",
                is_unit_registered: "yes",
                registered_title_type: "registered_contract",
                registration_completion_method: "direct_registration",
                registration_fees_payer: "buyer",
            },
        }),
        createSaleVariant({
            key: "inherited_sale",
            nameAr: "عقد بيع وحدة آلت بالميراث",
            documentTitleAr: "عقد بيع وحدة سكنية عن طريق الميراث",
            description: "للبيع الذي آلت فيه ملكية البائع بالميراث، مع إعلام الوراثة وسند تصرف باقي الورثة والحالات الخاصة.",
            sourceDocumentName: "عقد بيع وحدة عن طريق الورث (Z DRAFT).pdf",
            step: inheritedVariantStep,
            requiredClauseKeys: [...sourceClauses_1.saleSourceClauseKeysByVariant.inherited_sale],
            defaults: {
                ownership_source_type: "inheritance_declaration",
                is_unit_registered: "unknown",
                inheritance_disposition_basis: "sole_heir",
                minor_or_incapacitated_heirs: false,
            },
        }),
    ],
    optionalClauses: [
        {
            key: "sale_installment_schedule",
            nameAr: "إصدار ملحق جدول سداد الأقساط",
            documentTitleAr: "ملحق جدول سداد الأقساط",
            sourceDocumentName: "ملحق ( جدول الاقساط ) Z DRAFT.pdf",
            outputMode: "separate_annex",
            description: "يصدر كمستند مستقل مكمل لعقد البيع، ولا يطيل نص العقد الأساسي.",
            applicableVariantKeys: ["preliminary_sale", "registrable_sale", "inherited_sale"],
            insertBeforeStepKey: "sale_review",
            legalClauseKeys: [...sourceClauses_1.saleSourceClauseKeysByVariant.sale_installment_schedule],
            defaultFieldValues: {
                sale_payment_frequency: "monthly",
                sale_installment_primary_method: "cash_receipt",
                sale_installment_annex_copies_count: "2",
                sale_installment_rows: [],
                sale_early_payment_allowed: "yes",
                sale_installment_delay_treatment: "refer_to_main_contract",
                sale_installment_annex_acknowledged: false,
            },
            insertedSteps: [
                {
                    key: "sale_installment_schedule",
                    titleAr: "ملحق جدول الأقساط",
                    articleRange: "مستند منفصل",
                    sourceClauseKey: sourceClauses_1.saleSourceClauseKeysByVariant.sale_installment_schedule[0],
                    description: "تُستخدم هذه البيانات لإصدار ملحق مستقل يحمل مرجع عقد البيع.",
                    fields: [
                        { key: "sale_installment_annex_date", type: "date", labelAr: "تاريخ تحرير ملحق الأقساط", required: true },
                        { key: "sale_original_contract_date", type: "date", labelAr: "تاريخ عقد البيع الأصلي", required: true },
                        { key: "sale_contract_reference_number", type: "text", labelAr: "رقم عقد البيع أو مرجعه (إن وجد)" },
                        { key: "sale_installment_annex_copies_count", type: "number", labelAr: "عدد نسخ الملحق", required: true, validation: { min: 2, max: 20 } },
                        { key: "sale_down_payment", type: "money", labelAr: "قيمة المقدم المسدد", required: true, validation: { min: 0 } },
                        { key: "sale_remaining_amount", type: "money", labelAr: "إجمالي المبلغ المتبقي", required: true, validation: { min: 1 } },
                        { key: "sale_installments_count", type: "number", labelAr: "عدد الأقساط", required: true, validation: { min: 1, max: 240 } },
                        { key: "sale_installment_amount", type: "money", labelAr: "قيمة القسط القياسي", required: true, validation: { min: 1 } },
                        {
                            key: "sale_payment_frequency",
                            type: "select",
                            labelAr: "دورية السداد",
                            required: true,
                            options: [
                                { value: "monthly", labelAr: "شهرية" },
                                { value: "quarterly", labelAr: "ربع سنوية" },
                                { value: "semiannual", labelAr: "نصف سنوية" },
                                { value: "annual", labelAr: "سنوية" },
                                { value: "custom", labelAr: "مواعيد مخصصة" },
                            ],
                        },
                        { key: "sale_first_installment_date", type: "date", labelAr: "أول موعد استحقاق", required: true },
                        { key: "sale_installment_final_date", type: "date", labelAr: "آخر موعد استحقاق", required: true },
                        {
                            key: "sale_installment_primary_method",
                            type: "select",
                            labelAr: "طريقة السداد الأساسية",
                            required: true,
                            options: [
                                { value: "cash_receipt", labelAr: "نقدًا بموجب إيصال" },
                                { value: "bank_transfer", labelAr: "تحويل/إيداع بنكي" },
                                { value: "cheques", labelAr: "شيكات" },
                                { value: "wallet", labelAr: "محفظة إلكترونية" },
                                { value: "instapay", labelAr: "InstaPay" },
                            ],
                        },
                        {
                            key: "sale_installment_rows",
                            type: "repeater",
                            labelAr: "جدول الأقساط التفصيلي",
                            required: true,
                            minRows: 1,
                            columns: [
                                { key: "installment_no", type: "number", labelAr: "رقم القسط", required: true },
                                { key: "due_date", type: "date", labelAr: "تاريخ الاستحقاق", required: true },
                                { key: "amount", type: "money", labelAr: "قيمة القسط", required: true },
                                {
                                    key: "payment_method",
                                    type: "select",
                                    labelAr: "طريقة السداد",
                                    required: true,
                                    options: [
                                        { value: "cash_receipt", labelAr: "نقدي/إيصال" },
                                        { value: "bank_transfer", labelAr: "تحويل بنكي" },
                                        { value: "cheque", labelAr: "شيك" },
                                        { value: "wallet", labelAr: "محفظة/InstaPay" },
                                    ],
                                },
                                { key: "payment_date", type: "date", labelAr: "تاريخ السداد" },
                                { key: "receipt_reference", type: "text", labelAr: "رقم الإيصال/التحويل" },
                            ],
                        },
                        {
                            key: "sale_early_payment_allowed",
                            type: "radio",
                            labelAr: "هل يسمح بالسداد المبكر دون جزاء؟",
                            required: true,
                            options: [
                                { value: "yes", labelAr: "نعم" },
                                { value: "no", labelAr: "لا - يخضع لما يتفق عليه الطرفان" },
                            ],
                        },
                        {
                            key: "sale_installment_delay_treatment",
                            type: "select",
                            labelAr: "أثر التأخر المعتمد",
                            required: true,
                            options: [
                                { value: "refer_to_main_contract", labelAr: "تطبيق أحكام العقد الأصلي" },
                                { value: "approved_penalty", labelAr: "تطبيق تعويض/شرط جزائي معتمد" },
                                { value: "grace_period", labelAr: "مهلة محددة ثم تطبيق أحكام العقد" },
                            ],
                        },
                        {
                            key: "sale_installment_grace_days",
                            type: "number",
                            labelAr: "عدد أيام المهلة",
                            visibleWhen: { fieldKey: "sale_installment_delay_treatment", operator: "equals", value: "grace_period" },
                            validation: { min: 1, max: 365 },
                        },
                        { key: "sale_installment_annex_acknowledged", type: "checkbox", labelAr: "أقر بمراجعة بيانات ملحق الأقساط", required: true },
                    ],
                },
            ],
        },
    ],
    legalClauses: sourceClauses_1.saleSourceLegalClauses,
};
